Repository gitcoinco/web, pull requests merged in 2018-07, with the labels that each got.

#1591 adds help link to how it works dropdown
  app/assets/yge/youvegoteth/send.js
  app/retail/templates/shared/nav.html
Labels: in progress

#1587 Ensure avatar auth
  app/dashboard/views.py
Labels: in progress

#1585 Fix gas price settings css
  app/assets/v2/css/base.css
  app/assets/v2/js/pages/wallet_estimate.js
  app/dashboard/templates/shared/wallet_estimate.html
Labels: needs review

#1595 Upgrade Django to 2.0.7
  requirements/base.txt
Labels: backend, in progress, upgrade

#1600 added scott to the team page
  app/assets/v2/images/team/scott.jpg
  app/retail/views.py
Labels: in progress

#1601 email: reindent + update css
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/bounty_roundup.html
  app/retail/templates/emails/template.html
Labels: in progress

#1611 Add Joseph's testimonial
  app/assets/v2/images/testimonials/jschiarizzi.jpeg
  app/retail/views.py
Labels: in progress

#1619 gas advisories
  app/assets/v2/css/base.css
  app/assets/yge/css/main.css
  app/dashboard/templates/shared/gas_advisories.html
  app/dashboard/templates/shared/wallet_estimate.html
  app/dashboard/utils.py
  app/dashboard/views.py
  app/gas/admin.py
  app/gas/migrations/0003_gasadvisory.py
  app/gas/models.py
  app/gas/utils.py
  app/retail/templates/gas.html
Labels: in progress

#1572 Upgrade docker and travis to use Python 3.7
  .travis.yml
  Dockerfile
  app/app/travis.env
  docker-compose.yml
  requirements/base.txt
  scripts/deploy.bash
Labels: backend, in progress, needs review, upgrade

#1590 new metamask banner
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/current_balance.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/js/shared.js
  app/assets/yge/css/main.css
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/ens/account.html
  app/dashboard/templates/ens/base.html
  app/dashboard/templates/ens/ens.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/current_balance.html
  app/dashboard/templates/shared/no_issue_error.html
  app/dashboard/templates/shared/no_metamask_error.html
  app/dashboard/templates/shared/unlock_metamask.html
  app/dashboard/templates/shared/yge_auth.html
  app/dashboard/templates/shared/zero_balance_error.html
  app/dashboard/templates/submit_bounty.html
  app/external_bounties/templates/external_bounties.html
  app/external_bounties/templates/external_bounties_new.html
  app/external_bounties/templates/external_bounties_show.html
  app/retail/templates/shared/nav.html
Labels: needs review

#1628 as a issue submitter, i want diff issue templates for diff issue types on gitcoin/co repo, so i can have more customized templates to my use case
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/CUSTOM_ISSUE.md
  .github/ISSUE_TEMPLATE/DISCUSSION.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#1633 bug: set title attribute to null when switching to right network
  app/assets/v2/js/shared.js
Labels: in progress

#1637 Fix gas settings
  app/assets/v2/js/pages/wallet_estimate.js
Labels: in progress

#1639 Changes color of getting started from green to gc blue
  app/retail/templates/contributor_landing.html
Labels: in progress

#1514 Discord test button and send webhook msg with avatar
  app/app/urls.py
  app/dashboard/fixtures/initial.json
  app/dashboard/helpers.py
  app/dashboard/migrations/0088_auto_20180703_2056.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/views.py
  app/marketing/utils.py
  app/marketing/views.py
  app/retail/templates/settings/discord.html
Labels: in progress

#1635 Add Hotjar
  app/app/context.py
  app/app/settings.py
  app/retail/templates/shared/head.html
Labels: frontend, in progress

#1632 Newsletter PR (7/6)
  app/retail/emails.py
Labels: in progress

#1645 Implement management command 'sync_listener'
  app/dashboard/management/commands/sync_listener.py
  scripts/crontab
Labels: in progress

#1660 WIP: Fix record_bounty_activity..
  app/dashboard/helpers.py
  app/dashboard/management/commands/create_activity_records.py
Labels: backend, bounties, bug, in progress, wip

#1604 add Build Waiting State
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/images/icons/circle.png
  app/assets/v2/images/icons/clouds.png
  app/assets/v2/images/icons/cross.png
  app/assets/v2/images/rocket.svg
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/shared/bounty_waiting_state.html
Labels: in progress

#1651 hide network pill on mobile + reorder media query code
  app/assets/v2/css/base.css
Labels: frontend, in progress

#1657 Change 'not enabled this token'-banner color to orange.
  app/assets/v2/js/shared.js
  app/retail/templates/settings/tokens.html
Labels: frontend

#1689 contributor_landing: added newsletter
  app/retail/templates/contributor_landing.html
  app/retail/views.py
Labels: in progress

#1717 Improve the css for newsletter
  app/assets/v2/css/newsletter.css
  app/dashboard/templates/shared/newsletter.html
  app/retail/templates/contributor_landing.html
  app/retail/views.py
Labels: in progress

#1718 Makes get started button blue as suggested by Alisa
  app/retail/templates/landing/contributor/hero.html
Labels: in progress

#1719 Allow upto 4 cards in a row to utilise more space
  app/dashboard/templates/toolbox.html
Labels: in progress

#1726 updated 404 page
  app/assets/v2/css/base.css
  app/assets/v2/images/404.png
  app/retail/templates/error.html
Labels: in progress

#1648 gas estimation calculator on gas page
  app/assets/v2/js/base.js
  app/assets/v2/js/pages/gas.js
  app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
  app/assets/yge/youvegoteth/receive.js
  app/dashboard/views.py
  app/retail/templates/gas.html
Labels: in progress

#1730 no sumo popup if logged in
  app/retail/templates/shared/analytics.html
Labels: in progress

#1732 Activity stream
  app/app/sitemaps.py
  app/app/urls.py
  app/assets/v2/css/activity_stream.css
  app/dashboard/models.py
  app/dashboard/tokens.py
  app/retail/templates/activity.html
  app/retail/templates/shared/nav.html
  app/retail/templates/shared/pagination.html
  app/retail/views.py
Labels: in progress

#1736 onepages: updated to Muli & letter-spacing
  app/assets/onepager/css/main.css
Labels: in progress

#1729 Allow maxAge GET param for embed image responses
  app/dashboard/embed.py
  docs/README.md
Labels: backend, embedded, in progress, needs review

#1735 Gitcoin Newsletter (7/13)
  app/retail/emails.py
Labels: in progress

#1721 Bug - Misaligned Css On The Acceptance Page #1665
  app/dashboard/templates/shared/wallet_estimate.html
Labels: frontend

#1613 Make event names in slack notifications consistent
  app/dashboard/notifications.py
  app/dashboard/tests/test_dashboard_utils.py
  app/dashboard/utils.py
  app/marketing/management/commands/remarket_bounties.py
Labels: backend, dont merge, in progress, notifications, waiting on contributor

#1656 Fix Dai Value Bug Gitcoin Bot #1592
  app/dashboard/models.py
Labels: backend, bot, in progress

#1778 urls.py + about
  app/app/urls.py
  app/retail/templates/about.html
  app/retail/templates/community.html
Labels: in progress

#1775 Adds google optimize to contributor landing page
  app/retail/templates/contributor_landing.html
  app/retail/templates/shared/analytics.html
Labels: in progress

#1779 Disables editing of the issue title and description
  app/dashboard/templates/submit_bounty.html
Labels: in progress

#1780 Refactor GH issue details endpoint
  app/app/settings.py
  app/app/utils.py
  app/avatar/models.py
  app/avatar/utils.py
  app/avatar/views.py
  app/dashboard/embed.py
  app/dashboard/helpers.py
  app/dashboard/ios.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/tests/test_dashboard_helpers.py
  app/dashboard/tip_views.py
  app/dashboard/views.py
  app/external_bounties/management/commands/sync_known_github_repos.py
  app/external_bounties/models.py
  app/git/__init__.py
  app/git/apps.py
  app/git/migrations/__init__.py
  app/git/tests/test_utils.py
  app/git/utils.py
  app/gitcoinbot/actions.py
  app/gitcoinbot/management/commands/get_notifications.py
  app/marketing/management/commands/expiration_start_work.py
  app/marketing/management/commands/pull_github.py
  app/marketing/management/commands/sync_github.py
  app/marketing/stats.py
  requirements/base.txt
Labels: backend, in progress, mergeable

#1784 General lint/cleanup of tip views
  app/dashboard/tip_views.py
Labels: backend, in progress, linting

#1785 Replace disabled attribute with readonly for title and desc
  app/dashboard/templates/submit_bounty.html
Labels: in progress

#1787 attach job desc ux fixes
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/tag.css
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/shared/sidebar_search.html
  app/retail/templates/shared/result.html
Labels: in progress

#1795 Add gitcoin bounty details url to start work github bot copy
  app/dashboard/notifications.py
Labels: backend, bot, in progress, notifications

#1677 contributor : language specific impl
  app/app/urls.py
  app/assets/v2/js/shared.js
  app/dashboard/router.py
  app/dashboard/templates/profile_details.html
  app/retail/templates/contributor_landing.html
  app/retail/templates/landing/contributor/explorer.html
  app/retail/templates/landing/contributor/hero.html
  app/retail/views.py
Labels: in progress

#1800 restructuted profiles
  app/dashboard/templates/profiles/hidden.html
  app/dashboard/templates/profiles/organization.html
  app/dashboard/templates/profiles/profile.html
  app/dashboard/views.py
Labels: in progress

#1691 Presskit page #1683
  app/assets/v2/css/presskit.css
  app/assets/v2/images/presskit/GitCoinLogo.svg
  app/assets/v2/images/presskit/GitHubLogo.svg
  app/assets/v2/images/presskit/GitcoinLogoType.svg
  app/assets/v2/images/presskit/ZipFile.svg
  app/assets/v2/images/presskit/illustrations/divine.svg
  app/assets/v2/images/presskit/illustrations/helmet.svg
  app/assets/v2/images/presskit/illustrations/prime.svg
  app/assets/v2/images/presskit/illustrations/regulus.svg
  app/assets/v2/images/presskit/usage/gitcoin_logo_restrictions_1.svg
  app/assets/v2/images/presskit/usage/gitcoin_logo_restrictions_2.svg
  app/assets/v2/images/presskit/usage/gitcoin_logo_restrictions_3.svg
  app/assets/v2/images/presskit/usage/gitcoin_logo_restrictions_4.svg
  app/assets/v2/images/presskit/usage/gitcoin_logo_restrictions_5.svg
  app/assets/v2/images/presskit/usage/gitcoin_logo_restrictions_6.svg
  app/retail/templates/presskit.html
  app/retail/templates/presskit/colors.html
  app/retail/templates/presskit/illustrations.html
  app/retail/templates/presskit/logo.html
  app/retail/templates/presskit/resources.html
  app/retail/templates/presskit/usage.html
  app/retail/views.py
Labels: in progress

#1805 Fix division by zero error
  app/retail/utils.py
Labels: bug, community member

#971 Add autotranslate base
  Makefile
  app/app/settings.py
  app/locale/de/LC_MESSAGES/.!10498!django.mo
  app/locale/de/LC_MESSAGES/.!10523!django.mo
  app/locale/de/LC_MESSAGES/django.mo
  app/locale/de/LC_MESSAGES/django.po
  app/locale/de/LC_MESSAGES/djangojs.mo
  app/locale/de/LC_MESSAGES/djangojs.po
  app/locale/es/LC_MESSAGES/django.mo
  app/locale/es/LC_MESSAGES/django.po
  app/locale/es/LC_MESSAGES/djangojs.mo
  app/locale/es/LC_MESSAGES/djangojs.po
  app/locale/hi/LC_MESSAGES/django.mo
  app/locale/hi/LC_MESSAGES/django.po
  app/locale/hi/LC_MESSAGES/djangojs.mo
  app/locale/hi/LC_MESSAGES/djangojs.po
  app/locale/it/LC_MESSAGES/django.mo
  app/locale/it/LC_MESSAGES/django.po
  app/locale/it/LC_MESSAGES/djangojs.mo
  app/locale/it/LC_MESSAGES/djangojs.po
  app/locale/ko/LC_MESSAGES/django.mo
  app/locale/ko/LC_MESSAGES/django.po
  app/locale/ko/LC_MESSAGES/djangojs.mo
  app/locale/ko/LC_MESSAGES/djangojs.po
  app/locale/pl/LC_MESSAGES/django.mo
  app/locale/pl/LC_MESSAGES/django.po
  app/locale/pl/LC_MESSAGES/djangojs.mo
  app/locale/pl/LC_MESSAGES/djangojs.po
  app/locale/zh-hans/LC_MESSAGES/django.mo
  app/locale/zh-hans/LC_MESSAGES/django.po
  app/locale/zh-hans/LC_MESSAGES/djangojs.mo
  app/locale/zh-hans/LC_MESSAGES/djangojs.po
  app/locale/zh-hant/LC_MESSAGES/django.mo
  app/locale/zh-hant/LC_MESSAGES/django.po
  app/locale/zh-hant/LC_MESSAGES/djangojs.mo
  app/locale/zh-hant/LC_MESSAGES/djangojs.po
  app/marketing/views.py
  app/retail/templates/emails/start_work_rejected.html
  app/retail/templates/settings/email.html
  app/retail/templates/shared/nav.html
  requirements/base.txt
Labels: backend, translation

#1813 shows how it works on landing page / external nav
  app/retail/templates/shared/nav.html
Labels: in progress

#1810 Remove duplicate Tip properties
  app/dashboard/models.py
Labels: backend, bug, tips

#1311 WIP: Stats email v2
  app/dashboard/models.py
  app/retail/emails.py
  app/retail/templates/emails/quarterly_stats.html
Labels: community member, in progress, waiting on contributor, wip

#1776 Adds gasLimitEstimate for bulk payout
  app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
Labels: in progress

#1817 Fix checkbox icon
  app/assets/onepager/css/main.css
Labels: in progress

#1802 Utilize hosted IPFS node and fallback to Infura
  app/app/context.py
  app/app/settings.py
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/utils.py
  app/retail/templates/shared/footer_scripts.html
  docker-compose.yml
Labels: backend, devops, in progress

#1827 Change color of payout submit button
  app/dashboard/templates/bulk_payout_bounty.html
Labels: in progress

#1829 fix for stretched laptop on contributor landing page
  app/assets/v2/css/landing_page.css
  app/retail/templates/landing/contributor/hero.html
Labels: in progress

#1831 adds recent activity on funder landing page so ppl can see how active the site is
  app/retail/templates/index.html
  app/retail/templates/landing/contributor/activity.html
  app/retail/views.py
Labels: in progress

#1833 contributor page: css updates
  app/assets/v2/css/landing_page.css
  app/retail/templates/contributor_landing.html
  app/retail/templates/landing/contributor/activity.html
  app/retail/templates/shared/activity.html
Labels: in progress

#1755 [WIP] UI Inventory
  app/app/urls.py
  app/assets/v2/css/rain.css
  app/assets/v2/css/tabs.css
  app/assets/v2/js/pages/tabs.js
  app/retail/templates/ui_inventory.html
  app/retail/views.py
  docs/CONTRIBUTING.md
Labels: frontend, wip

#1845 Visually improves the readonly fields
  app/assets/v2/css/submit_bounty.css
  app/dashboard/templates/submit_bounty.html
Labels: in progress

#1849 css: display filter tags + sort on mobile
  app/assets/v2/css/base.css
  app/assets/v2/css/search_bar.css
Labels: frontend

#1862 css: minor refactor
  app/assets/v2/css/base.css
  app/dashboard/templates/submit_bounty.html
Labels: in progress
