Repository gitcoinco/web, pull requests merged in 2018-12, with the labels that each got.

#2970 Issue Explorer: Moving expiry date to flyout.
  app/assets/v2/css/base.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/js/shared.js
  app/dashboard/templates/shared/bounty-popover.html
Labels: frontend, needs review, needs-testing

#3053 Ks fund miner fixes
  app/assets/v2/js/grants/fund.js
Labels: in progress

#3056 add network to new.js
  app/assets/v2/js/grants/new.js
  app/grants/templates/grants/new.html
Labels: in progress

#3052 Ks successful contribution def
  app/app/urls.py
  app/grants/migrations/0003_auto_20181203_2043.py
  app/grants/models.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/grants/successful_contribution.html
  app/retail/templates/emails/grants/successful_contribution.txt
Labels: in progress

#3063 grant/thank_you : fix image overlap
  app/retail/templates/emails/grants/thank_you_for_supporting.html
Labels: in progress

#3064 grants/email: unify button size
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/successful_contribution.html
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
  app/retail/templates/emails/grants/transaction_summary.html
  app/retail/templates/emails/grants/update_notification.html
Labels: in progress

#3061 Add transaction url in waiting state
  app/assets/v2/js/grants/new.js
Labels: in progress

#3066 grant/new -> get network from document.web3network
  app/assets/v2/js/grants/new.js
Labels: in progress

#3068 grant/email: fix default image in email
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/successful_contribution.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
Labels: Gitcoin Emails, frontend, in progress

#2130 [WOC] Wagtail - Developer & Funder Guides
  app/app/settings.py
  app/app/urls.py
  app/assets/v2/css/guide.css
  app/assets/v2/css/toolbox.css
  app/assets/v2/images/browser_extension.png
  app/assets/v2/images/compass.png
  app/assets/v2/images/issue_explorer.png
  app/assets/v2/js/toolbox.js
  app/cms/__init__.py
  app/cms/fixtures/guides.json
  app/cms/migrations/0001_initial.py
  app/cms/migrations/__init__.py
  app/cms/models.py
  app/cms/templates/cms/guide_page.html
  requirements/base.txt
Labels: waiting on contributor

#2563 Basic Payout - Implement Display of User Icon and Address
  app/assets/v2/css/gitcoin.css
  app/assets/v2/js/pages/process_bounty.js
  app/dashboard/templates/process_bounty.html
  app/dashboard/views.py
Labels: frontend, needs review

#3085 grants/new: updated look & feel
  app/assets/v2/css/grants/new.css
  app/grants/templates/grants/new.html
Labels: Gitcoin Grants, enhancement, frontend

#3047 Accessory - Deadpool Mask
  app/assets/v2/images/avatar/Accessories/Masks-deadpool.svg
  app/avatar/templates/accessories/masks/deadpool.txt
  app/avatar/utils.py
Labels: Gitcoin Avatar

#3081 kevin grant updates 2018/12/04
  app/assets/v2/js/grants/fund.js
  app/grants/abi.py
  app/grants/admin.py
  app/grants/models.py
  app/grants/templates/grants/fund.html
  docs/GRANTS.md
  pydocmd.yml
Labels: in progress

#3109 grant/form : set token value min to 0.001
  app/assets/v2/css/grants/fund.css
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
Labels: in progress

#3107 fix suggest kudos loading
  app/dashboard/templates/process_bounty.html
Labels: in progress

#3019 moves blocked users into a DB model from env variable
  app/app/pipeline.py
  app/app/settings.py
  app/avatar/views.py
  app/dashboard/helpers.py
  app/dashboard/management/commands/sync_profiles.py
  app/dashboard/migrations/0125_blockeduser.py
  app/dashboard/migrations/0126_auto_20181205_1652.py
  app/dashboard/models.py
  app/dashboard/utils.py
Labels: in progress

#3096 Kudos Performance / Unveil
  app/kudos/templates/kudos_marketplace.html
  app/kudos/templates/shared/kudos_card.html
Labels: Gitcoin Kudos, enhancement, frontend, needs review

#3117 Ks approve fix
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/new.js
  app/grants/admin.py
  app/grants/forms.py
  app/grants/migrations/0006_auto_20181206_1815.py
  app/grants/migrations/0007_auto_20181207_1721.py
  app/grants/models.py
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/views.py
  app/retail/templates/emails/grants/grant_cancellation.html
  app/retail/templates/emails/grants/grant_cancellation.txt
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/new_supporter.html
  app/retail/templates/emails/grants/new_supporter.txt
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/successful_contribution.html
  app/retail/templates/emails/grants/successful_contribution.txt
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
  app/retail/templates/emails/grants/thank_you_for_supporting.txt
  app/retail/templates/emails/grants/transaction_summary.html
  app/retail/templates/emails/grants/update_notification.html
Labels: in progress

#3133 Fixing sentry bugs in bounty creation
  app/assets/v2/js/shared.js
Labels: in progress

#3134 shared : fixed incorrect var scope
  app/assets/v2/js/grants/shared.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
Labels: in progress

#3136 grant/new: add image
  app/assets/v2/images/grants/new.svg
  app/grants/templates/grants/new.html
Labels: Gitcoin Grants, in progress

#3153 reject token usage
  app/assets/v2/js/pages/tokens_settings.js
Labels: Gitcoin.co, bug, frontend

#2725 Semaphore changes
  app/app/utils.py
  app/dashboard/helpers.py
  app/dashboard/utils.py
Labels: backend, needs review, needs-testing

#3137 adding network option
  app/assets/v2/css/grants/grant.css
  app/assets/v2/js/grants/index.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/shared.js
  app/grants/templates/grants/index.html
  app/grants/templates/grants/milestones.html
  app/grants/views.py
Labels: Gitcoin Grants, in progress

#3126 Error handling for non-usdt convertible tokens
  app/grants/models.py
Labels: in progress

#3154 grant/new: add gas-setting
  app/assets/v2/css/base.css
  app/assets/v2/css/grants/fund.css
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/new.js
  app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
  app/assets/v2/js/pages/wallet_estimate.js
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/shared/wallet_estimate.html
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/views.py
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/support_cancellation.txt
Labels: in progress

#3130 add alert and disable button to prevent contributions on different ne…
  app/assets/v2/js/grants/fund.js
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
Labels: in progress

#3093 Ks miner fixes
  app/grants/management/commands/subminer.py
  app/grants/migrations/0006_auto_20181205_2310.py
  app/grants/migrations/0008_merge_20181210_1746.py
  app/grants/models.py
  app/retail/emails.py
Labels: in progress

#3163 tags exceeding profile page
  app/assets/v2/css/dashboard.css
Labels: enhancement, frontend, needs review

#3169 grant/milestone revamp
  app/assets/v2/css/grants/milestones.css
  app/assets/v2/images/list-icon-green.svg
  app/assets/v2/images/list-icon.svg
  app/assets/v2/js/grants/milestones.js
  app/grants/forms.py
  app/grants/templates/grants/milestones.html
Labels: Gitcoin Grants, in progress

#3127 sets num kudos limit higher
  app/kudos/views.py
Labels: in progress

#3181 grant/details: updated activity section
  app/assets/v2/css/base.css
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/shared.js
  app/grants/templates/grants/detail.html
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/support_cancellation.txt
Labels: Gitcoin Grants

#3179 Adjust logging and return types for non-gc schema bounties
  app/assets/v2/js/pages/kudos_send.js
  app/dashboard/helpers.py
Labels: backend, in progress

#3182 grants/email
  app/grants/templates/grants/detail.html
  app/retail/templates/emails/grants/grant_cancellation.html
  app/retail/templates/emails/grants/grant_cancellation.txt
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/subscription_terminated.txt
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/transaction_summary.html
  app/retail/templates/emails/grants/transaction_summary.txt
  app/retail/templates/emails/grants/update_notification.html
  app/retail/templates/emails/grants/update_notification.txt
Labels: in progress

#3187 Remove redundant/secondary import of Profile and fix operator space in cleanup_dupe
  app/dashboard/management/commands/cleanup_dupe_profiles.py
Labels: backend, bug, needs review

#3183 terms: updated terms & conditions
  app/dashboard/templates/legal/terms.html
Labels: in progress

#3190 newsletter 12/12
  app/retail/emails.py
Labels: in progress

#3193 feedback emails come from alisa / frank, not kevin
  app/marketing/mails.py
  app/retail/emails.py
Labels: in progress

#3185 Kudos image size on github comment
  app/dashboard/notifications.py
Labels: in progress

#3201 Make links on profiles and add usernamew
  app/grants/templates/grants/card/front.html
  app/grants/templates/grants/detail.html
Labels: in progress

#3202 css: fixed orgs in profile
  app/assets/v2/css/profile.css
  app/dashboard/templates/profiles/profile.html
Labels: Gitcoin Profile, frontend, in progress

#3192 Ks tx data
  app/assets/v2/css/grants/grant.css
  app/assets/v2/js/grants/index.js
  app/grants/models.py
  app/grants/templates/grants/banner.html
  app/grants/templates/grants/card/front.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/profile/body.html
  app/grants/templates/grants/profile/index.html
  app/grants/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/grants/grant_cancellation.html
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/new_supporter.html
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/successful_contribution.html
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
Labels: in progress

#3204 profile: updated hidden profile -> with obiwan
  app/dashboard/templates/profiles/hidden.html
  app/dashboard/templates/profiles/profile.html
Labels: Gitcoin Profile, frontend, in progress

#3205 fix suggestions, validations onload
  app/assets/v2/js/pages/process_bounty.js
Labels: in progress

#3199 gitcoin/terms: updated content
  app/dashboard/templates/legal/terms.html
Labels: Gitcoin Grants, Gitcoin.co, in progress

#3212 Add transaction link and url link in all waiting state pages
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/fund.js
Labels: in progress

#3228 labs: card margin fix
  app/dashboard/templates/labs.html
Labels: in progress

#3214 limit grant image to 250kb
  app/assets/v2/js/grants/new.js
Labels: Gitcoin Grants, in progress

#3225 Fund with decimal, remove nonce, make recurring funding work
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/compiledSubscriptionContract.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/new.js
  app/grants/abi.py
  app/grants/migrations/0009_auto_20181213_2243.py
  app/grants/migrations/0010_merge_20181217_2034.py
  app/grants/migrations/0011_auto_20181217_2122.py
  app/grants/models.py
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/views.py
Labels: Gitcoin Grants, in progress

#3251 Grants/details: Add gas settings on cancel grants
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
  app/grants/templates/grants/detail.html
  app/grants/views.py
Labels: in progress

#2965 [WIP] Cancel bounties reason
  app/app/urls.py
  app/assets/v2/css/forms/radio.css
  app/assets/v2/js/pages/kill_bounty.js
  app/dashboard/migrations/0127_bounty_canceled_bounty_reason.py
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/bounty/kill.html
  app/dashboard/templates/shared/bounty_actions_hidden_vars.html
  app/dashboard/views.py
Labels: Gitcoin Bounties, in progress, needs review

#3227 Cleanup for Labs
  app/dashboard/migrations/0003_labsresearch_upcoming.py
  app/dashboard/models.py
  app/dashboard/templates/labs.html
Labels: Gitcoin Labs, waiting on contributor

#3339 grants: add qa
  app/assets/v2/css/kudos/styles.css
  app/grants/templates/grants/faq.html
  app/grants/templates/grants/quickstart.html
  app/kudos/templates/kudos_about.html
Labels: Gitcoin Grants

#3324 grants: disable cancel action if metamask address doesn't match
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/shared.js
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/detail.html
Labels: Gitcoin Grants
