Repository gitcoinco/web, pull requests merged in 2018-03, with the labels that each got.

#387 Adding token conversion rate to bounties
  app/assets/legacy/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/embed.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/router.py
  app/dashboard/templates/bounty_details.html
  app/economy/utils.py
  app/marketing/mails.py
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/bounty.txt
Labels: backend, enhancement

#514 WIP: Add form styles
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/button.css
  app/assets/v2/css/forms/checkbox.css
  app/assets/v2/css/forms/form.css
  app/assets/v2/css/forms/input.css
  app/assets/v2/css/forms/label.css
  app/assets/v2/css/forms/radio.css
  app/assets/v2/css/forms/select.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/images/arrow-down.png
  app/assets/v2/images/check.svg
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/metamask_estimate.html
  app/dashboard/templates/shared/name.html
  app/dashboard/templates/shared/notification_email.html
  app/dashboard/templates/shared/sidebar_search.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/templates/svgs/arrow-down.svg
  app/retail/templates/email_settings.html
  app/retail/templates/save_search.html
  app/retail/templates/shared/head.html
  app/retail/templates/slack.html
  app/retail/templates/whitepaper_new.html
Labels: enhancement, frontend, ui, wip

#539 FIX: Replace selects with select2 and update arrow
  app/assets/v2/css/forms/select.css
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/templates/submit_bounty.html
Labels: bug, frontend, ui

#549 Unify navbar template
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/external_bounties.html
  app/dashboard/templates/external_bounties_show.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/ios.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/profile_details.html
  app/dashboard/templates/shared/nav_internal.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/templates/toolbox.html
  app/retail/templates/base.html
  app/retail/templates/leaderboard.html
  app/retail/templates/shared/nav.html
  app/retail/templatetags/is_in_list.py
Labels: frontend, in progress, nav, ui

#545 Add initial changelog
  CHANGELOG.md
  README.md
Labels: docs

#523 core: Rebirth of the explorer
  app/assets/v2/css/base.css
  app/assets/v2/css/current_balance.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/external_bounties/checkboxes.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/css/tag.css
  app/assets/v2/js/base.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/shared/current_balance.html
  app/dashboard/templates/shared/search_bar.html
  app/dashboard/templates/shared/sidebar_search.html
Labels: frontend, mergeable, ui, wip

#558 review: added feedback for the explorer page
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/images/comment.svg
  app/dashboard/templates/dashboard.html
Labels: frontend, needs review

#559 css : fixed display for devices below 380px
  app/assets/v2/css/dashboard.css
Labels: bug, frontend, mobile

#562 Added remove filter functionality for Search Tags
  app/assets/v2/js/pages/dashboard.js
Labels: bug, explorer, frontend, in progress, mergeable

#568 sendgrid event hooks
  app/app/settings.py
  app/app/urls.py
  app/marketing/admin.py
  app/marketing/migrations/0016_emailevent.py
  app/marketing/models.py
  app/marketing/webhookviews.py
Labels: backend, emails, in progress

#544 show tips on leaderboard / profiles
  app/assets/v2/css/base.css
  app/dashboard/models.py
  app/dashboard/templates/profile_details.html
  app/dashboard/views.py
Labels: in progress, leaderboard, profile

#581 Feature/faucet -- with kevin's changes
  app/app/settings.py
  app/app/urls.py
  app/assets/v2/css/base.css
  app/assets/v2/css/faucet.css
  app/assets/v2/css/forms/form.css
  app/assets/v2/images/gas.png
  app/assets/v2/images/gas.svg
  app/assets/v2/js/pages/faucet_form.js
  app/assets/v2/js/pages/process_faucet.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/svgs/gas.svg
  app/dashboard/templates/svgs/success.svg
  app/faucet/__init__.py
  app/faucet/admin.py
  app/faucet/migrations/0001_initial.py
  app/faucet/migrations/__init__.py
  app/faucet/models.py
  app/faucet/templates/faucet_form.html
  app/faucet/templates/process_faucet_request.html
  app/faucet/templates/shared/faucet_network_status.html
  app/faucet/templates/shared/faucet_no_metamask_error.html
  app/faucet/templates/shared/faucet_over_balance_error.html
  app/faucet/templates/shared/faucet_unlock_metamask.html
  app/faucet/views.py
  app/github/utils.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/faucet_request.html
  app/retail/templates/emails/faucet_request.txt
  app/retail/templates/shared/head.html
Labels: in progress

#573 css: refactored media queries
  app/assets/v2/css/dashboard.css
  app/dashboard/templates/dashboard.html
Labels: frontend, mobile, needs review, needs-testing

#577 Cleanup syntax and linting issues for backend code
  app/app/settings.py
  app/app/sitemaps.py
  app/app/urls.py
  app/credits/admin.py
  app/credits/apps.py
  app/credits/models.py
  app/credits/tests.py
  app/credits/views.py
  app/dashboard/admin.py
  app/dashboard/embed.py
  app/dashboard/ios.py
  app/dashboard/management/commands/activity_report.py
  app/dashboard/management/commands/post_to_craigslist.py
  app/dashboard/management/commands/sync_profiles.py
  app/dashboard/models.py
  app/dashboard/signals.py
  app/dashboard/tests.py
  app/dashboard/utils.py
  app/dashboard/views.py
  app/gas/admin.py
  app/gas/management/commands/sync_gas_prices.py
  app/gas/models.py
  app/gas/tests.py
  app/gas/utils.py
  app/gas/views.py
  app/legacy/urls.py
  app/linkshortener/admin.py
  app/linkshortener/apps.py
  app/linkshortener/models.py
  app/linkshortener/tests.py
  app/marketing/admin.py
  app/marketing/apps.py
  app/marketing/google_analytics.py
  app/marketing/mails.py
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/management/commands/expiration_tip.py
  app/marketing/management/commands/ingest_slack_users.py
  app/marketing/management/commands/pull_github.py
  app/marketing/management/commands/pull_stats.py
  app/marketing/management/commands/remarket_tweet.py
  app/marketing/management/commands/sync_github.py
  app/marketing/management/commands/sync_mail.py
  app/marketing/management/commands/sync_slack.py
  app/marketing/management/commands/test_email.py
  app/marketing/models.py
  app/marketing/tests.py
  app/marketing/utils.py
  app/retail/admin.py
  app/retail/apps.py
  app/retail/emails.py
  app/retail/helpers.py
  app/retail/models.py
  app/retail/tests.py
  app/retail/utils.py
  app/retail/views.py
  app/tdi/admin.py
  app/tdi/apps.py
  app/tdi/models.py
  app/tdi/tests.py
  app/tdi/views.py
Labels: backend, in progress, linting

#524 Writing coverage for marketing model, increasing coverage to 33%
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/management/commands/expiration_start_work.py
  app/marketing/management/commands/send_subscription_mails.py
  app/marketing/tests/management/commands/test_assemble_leaderboards.py
  app/marketing/tests/management/commands/test_expiration.py
  app/marketing/tests/management/commands/test_expiration_start_work.py
  app/marketing/tests/management/commands/test_expiration_tip.py
  app/marketing/tests/management/commands/test_remarket_tweet.py
  app/marketing/tests/management/commands/test_roundup.py
  app/marketing/tests/management/commands/test_send_subscription_mails.py
  app/marketing/tests/management/commands/test_sync_keywords.py
  app/marketing/tests/test_marketing_utils.py
Labels: backend, mergeable, tests

#236 BOT / GITHUB INTEGRATION REVAMP MVP
  app/app/local_settings.py.dist
  app/app/settings.py
  app/app/urls.py
  app/assets/v2/js/tokens.js
  app/assets/yge/youvegoteth/new.js
  app/assets/yge/youvegoteth/send.js
  app/dashboard/views.py
  app/gitcoinbot/README.md
  app/gitcoinbot/__init__.py
  app/gitcoinbot/actions.py
  app/gitcoinbot/apps.py
  app/gitcoinbot/migrations/__init__.py
  app/gitcoinbot/tests.py
  app/gitcoinbot/views.py
  requirements/base.txt
Labels: backend, needs review, needs-testing, to do

#599 Check dict existence in gitcoin bot payload view
  app/gitcoinbot/views.py
Labels: backend, bot, bug, in progress

#579 removes optional add_bcc option from mailer
  app/app/local_settings.py.dist
  app/dashboard/management/commands/activity_report.py
  app/marketing/mails.py
Labels: backend, emails, in progress, mergeable

#591 slack notifications upon start / stop work
  app/dashboard/models.py
Labels: backend, in progress, mergeable, notifications

#566 mocks expiration date on standardbounties
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/utils.py
Labels: bounties, frontend, in progress, mergeable

#622 fix for empty github notification
  app/dashboard/utils.py
Labels: backend, bug, in progress, mergeable, notifications

#468 ESLint configuration to help code with more style
  .eslintignore
  .eslintrc
  .eslintrc.yml
  app/assets/legacy/v2/js/abi.js
  app/assets/legacy/v2/js/amounts.js
  app/assets/legacy/v2/js/base.js
  app/assets/legacy/v2/js/pages/bounty_details.js
  app/assets/legacy/v2/js/pages/claim_bounty.js
  app/assets/legacy/v2/js/pages/clawback_expired_bounty.js
  app/assets/legacy/v2/js/pages/dashboard.js
  app/assets/legacy/v2/js/pages/process_bounty.js
  app/assets/legacy/v2/js/shared.js
  app/assets/legacy/v2/js/tokens.js
  app/assets/v2/js/abi.js
  app/assets/v2/js/amounts.js
  app/assets/v2/js/base.js
  app/assets/v2/js/ipfs.js
  app/assets/v2/js/note.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/carousel.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/faucet_form.js
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/kill_bounty.js
  app/assets/v2/js/pages/leaderboard.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/assets/v2/js/pages/process_faucet.js
  app/assets/v2/js/pages/shared_bounty_mutation_estimate_gas.js
  app/assets/v2/js/shared.js
  app/assets/v2/js/tokens.js
  app/assets/v2/js/toolbox.js
  app/assets/v2/js/waiting_room_entertainment.js
  app/assets/v2/js/work_with_gitcoin.js
  app/assets/yge/ethereumjs/example.js
  app/assets/yge/redeem_coin.js
  app/assets/yge/youvegoteth/index.js
  app/assets/yge/youvegoteth/new.js
  app/assets/yge/youvegoteth/pre.js
  app/assets/yge/youvegoteth/receive.js
  app/assets/yge/youvegoteth/send.js
  app/assets/yge/youvegoteth/shared.js
  app/assets/yge/youvegoteth/tokens.js
  app/assets/yge/youvegoteth/web3alert.js
  docs/CONTRIBUTING.md
  package.json
Labels: frontend

#624 Enable ESLint in pre-commit and on Travis CI
  .eslintrc
  .pre-commit-config.yaml
  .travis.yml
Labels: frontend, in progress, linting, mergeable, travis

#610 Sends followup emails after 48 emails to bounty fulfiller and submitter
  app/app/urls.py
  app/marketing/mails.py
  app/marketing/management/commands/bounty_feedback_email.py
  app/marketing/webhookviews.py
  app/retail/emails.py
  app/retail/templates/emails/txt.html
  app/retail/templates/emails/txt.txt
  scripts/crontab
Labels: backend, bounties, emails, in progress

#606 tooltip: updated as per review comments
  app/assets/v2/css/base.css
  app/dashboard/templates/shared/status_tooltip.html
Labels: frontend, mergeable, ui, wip

#586 nav: redesigned the dropdown
  app/assets/v2/css/gitcoin.css
  app/dashboard/templates/shared/nav_auth.html
Labels: community member, frontend, in progress, navbar, ui

#629 nav: redesigned the dropdown
  app/assets/v2/css/gitcoin.css
  app/dashboard/templates/shared/nav_auth.html
Labels: enhancement, frontend, ui

#630 css: dropdown fix
  app/assets/v2/css/gitcoin.css
Labels: frontend, ui

#589 destroys legacy bounty handling code (except for on legacy kill bounty page)
  .eslintrc
  app/app/urls.py
  app/assets/legacy/v2/js/abi.js
  app/assets/legacy/v2/js/amounts.js
  app/assets/legacy/v2/js/base.js
  app/assets/legacy/v2/js/pages/bounty_details.js
  app/assets/legacy/v2/js/pages/claim_bounty.js
  app/assets/legacy/v2/js/pages/clawback_expired_bounty.js
  app/assets/legacy/v2/js/pages/dashboard.js
  app/assets/legacy/v2/js/pages/process_bounty.js
  app/assets/legacy/v2/js/shared.js
  app/assets/legacy/v2/js/tokens.js
  app/assets/legacy/yge/ethereumjs/ethereumjs-accounts.js
  app/assets/legacy/yge/ethereumjs/hooked-web3-provider.js
  app/assets/legacy/yge/ethereumjs/tx.js
  app/assets/legacy/yge/ethereumjs/web3.js
  app/assets/v2/js/abi.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/legacy_kill_bounty.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/views.py
  app/legacy/__init__.py
  app/legacy/apps.py
  app/legacy/helpers.py
  app/legacy/urls.py
  app/legacy/views.py
Labels: in progress, legacy

#359 Environment variable setting handling
  .gitignore
  .travis.yml
  README.md
  app/app/local.env
  app/app/local_settings.py.dist
  app/app/settings.py
  app/app/travis.env
  bin/docker-command.bash
  docker-compose.yml
  readme_runninglocally.md
  requirements/base.txt
Labels: backend, in progress

#621 explorer: updated view
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/shared/search_bar.html
  app/dashboard/templates/shared/sidebar_search.html
Labels: explorer, frontend, ui

#638 use AGPLv3 license
  package.json
Labels: frontend

#553 Update all alerts to include new alert style
  app/assets/v2/css/base.css
  app/assets/v2/images/close.svg
  app/assets/v2/images/info.svg
  app/assets/v2/images/success.svg
  app/assets/v2/images/warning.svg
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/kill_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/assets/v2/js/shared.js
  app/assets/yge/redeem_coin.js
  app/assets/yge/youvegoteth/new.js
  app/assets/yge/youvegoteth/receive.js
  app/assets/yge/youvegoteth/send.js
  app/assets/yge/youvegoteth/web3alert.js
Labels: frontend, mergeable, ui

#644 Redesign and implementation of embed widget
  app/assets/v2/fonts/futura/FuturaStd-Medium.otf
  app/assets/v2/images/embed-widget/background.png
  app/dashboard/embed.py
Labels: embedded

#661 no faucet spoofing
  app/faucet/views.py
Labels: in progress

#662 no faucet spoofing
  app/faucet/views.py
Labels: in progress

#645 Adds testimonial video to landing page
  app/retail/templates/shared/testimonials.html
Labels: in progress

#663 People shouldn't be able to start work on more than 3 issues at a time
  app/assets/v2/js/shared.js
  app/dashboard/views.py
Labels: in progress

#664 Records UserAction events for Tip, Start/Stop Work, and Bounty related things
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/helpers.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/views.py
Labels: in progress

#571 Inline validations
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/checkbox.css
  app/assets/v2/css/forms/input.css
  app/assets/v2/images/close-red.png
  app/assets/v2/images/success.png
  app/assets/v2/js/amounts.js
  app/assets/v2/js/ipfs.js
  app/assets/v2/js/jquery.validate.min.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/kill_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/tokens.js
  app/assets/yge/redeem_coin.js
  app/assets/yge/youvegoteth/new.js
  app/assets/yge/youvegoteth/receive.js
  app/assets/yge/youvegoteth/send.js
  app/assets/yge/youvegoteth/tokens.js
  app/assets/yge/youvegoteth/web3alert.js
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/notification_email.html
  app/dashboard/templates/submit_bounty.html
  app/retail/templates/email_settings.html
  app/retail/templates/shared/footer_scripts.html
  app/retail/templates/slack.html
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement, frontend, mergeable, ui

#673 Offchain Bounties
  app/app/settings.py
  app/app/sitemaps.py
  app/app/urls.py
  app/assets/v2/css/external_bounties/bounties.css
  app/assets/v2/css/external_bounties/bounty.css
  app/assets/v2/images/background.png
  app/assets/v2/js/note.js
  app/assets/v2/js/pages/offchain_bounties.js
  app/external_bounties/__init__.py
  app/external_bounties/admin.py
  app/external_bounties/apps.py
  app/external_bounties/forms.py
  app/external_bounties/migrations/0001_initial.py
  app/external_bounties/migrations/__init__.py
  app/external_bounties/models.py
  app/external_bounties/router.py
  app/external_bounties/templates/external_bounties.html
  app/external_bounties/templates/external_bounties_new.html
  app/external_bounties/templates/external_bounties_show.html
  app/external_bounties/views.py
  app/marketing/mails.py
  app/retail/templates/shared/head.html
  readme_api.md
Labels: bounties, external, in progress, ui

#635 fontawesome: upgrade to v5
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/carousel.css
  app/assets/v2/css/current_balance.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/newsletter.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/js/fontawesome-all.min.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/shared.js
  app/assets/yge/css/font-awesome.min.css
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/templates/shared/newsletter.html
  app/dashboard/templates/shared/sidebar_search.html
  app/retail/templates/help.html
  app/retail/templates/shared/head.html
  app/retail/templates/shared/hero.html
  app/retail/templates/shared/mailchimp.html
  app/retail/templates/shared/nav.html
  app/retail/templates/shared/testimonials.html
  app/retail/templates/slack.html
Labels: frontend, upgrade

#677 changed all target=new to target=_blank with rel=noopener
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/assets/yge/redeem_coin.js
  app/assets/yge/youvegoteth/receive.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/profile_details.html
  app/dashboard/templates/shared/metamask_estimate.html
  app/dashboard/templates/shared/unlock_metamask.html
  app/dashboard/templates/shared/zero_balance_error.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/templates/yge/send2.html
  app/faucet/templates/shared/faucet_no_metamask_error.html
  app/faucet/templates/shared/faucet_unlock_metamask.html
  app/retail/templates/gas.html
  app/retail/templates/getgitcoin.html
  app/retail/templates/help.html
  app/retail/templates/index.html
  app/retail/templates/shared/footer.html
  app/retail/templates/shared/hero.html
Labels: enhancement, frontend

#657 Add GeoIP2 and lang middleware
  Dockerfile
  app/app/settings.py
  app/app/utils.py
  app/dashboard/migrations/0046_auto_20180319_1329.py
  app/dashboard/models.py
  app/github/middleware.py
  app/github/views.py
  app/marketing/management/commands/pull_stats.py
  readme_runninglocally.md
  requirements/base.txt
Labels: backend, in progress, needs review, needs-testing

#626 Integrate StandardBounties increasePayout()
  app/app/urls.py
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/shared.js
  app/dashboard/helpers.py
  app/dashboard/notifications.py
  app/dashboard/templates/increase_bounty.html
  app/dashboard/tests/test_notifications.py
  app/dashboard/views.py
Labels: backend, bounties, waiting on contributor

#709 workaround for web3 sync issues
  app/dashboard/views.py
Labels: in progress

#641 @gitcoinbot tune up!
  app/gitcoinbot/actions.py
  app/gitcoinbot/admin.py
  app/gitcoinbot/migrations/0001_initial.py
  app/gitcoinbot/models.py
  app/gitcoinbot/tests/test_gitcoinbot_actions.py
  app/gitcoinbot/views.py
Labels: backend, bot

#711 bounty: review feedback added
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: frontend, needs design, ui

#731 fixed broken save search UI & missing save search text on mobile
  app/assets/v2/css/base.css
  app/assets/v2/css/search_bar.css
Labels: frontend, ui

#729 accepted_on date in fulfillment model
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0048_auto_20180328_0829.py
  app/dashboard/migrations/0049_auto_20180328_0832.py
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/bounty_details.html
Labels: in progress

#739 html: removed extra css link from header.html
  app/retail/templates/shared/head.html
Labels: bug, frontend

#740 html: reordered css links
  app/dashboard/templates/bounty_details.html
Labels: bounties, frontend

#675 Issue funder can remove users from issue
  app/app/tests/test_app_urls.py
  app/app/urls.py
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/dashboard/models.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/views.py
  app/marketing/mails.py
  app/marketing/management/commands/test_email.py
  app/retail/emails.py
  app/retail/templates/emails/bounty_uninterested.html
  app/retail/templates/emails/bounty_uninterested.txt
Labels: backend, bounties, frontend, mergeable

#741 bounty: css fix for wonky contributor info
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
Labels: frontend

#697 css: sidebar fixup
  app/assets/v2/css/toolbox.css
  app/dashboard/templates/toolbox.html
Labels: frontend

#738 bounty: display submit only on starting work
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/bounty_details.html
Labels: bounties, frontend
