Repository gitcoinco/web, pull requests merged in 2018-08, with the labels that each got.

#1846 Sentry integration
  app/app/context.py
  app/app/settings.py
  app/app/templates/shared/rollbar.html
  app/app/templates/shared/sentry.html
  app/app/utils.py
  app/app/wsgi.py
  app/dashboard/management/commands/sync_geth.py
  app/dashboard/notifications.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/bulk_payout_bounty.html
  app/dashboard/templates/contribute_bounty.html
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/ftux/onboard.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/ios.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/onepager/base.html
  app/dashboard/templates/payout_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/profiles/profile.html
  app/dashboard/templates/quickstart.html
  app/dashboard/templates/social_contribution.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/templates/toolbox.html
  app/dashboard/utils.py
  app/external_bounties/templates/external_bounties.html
  app/external_bounties/templates/external_bounties_new.html
  app/external_bounties/templates/external_bounties_show.html
  app/git/utils.py
  app/gitcoinbot/actions.py
  app/retail/templates/about.html
  app/retail/templates/activity.html
  app/retail/templates/base.html
  app/retail/templates/contributor_landing.html
  app/retail/templates/help.html
  app/retail/templates/how_it_works.html
  app/retail/templates/index.html
  app/retail/templates/leaderboard.html
  app/retail/templates/mission.html
  app/retail/templates/presskit.html
  app/retail/templates/results.html
  app/retail/templates/vision.html
  docs/ENVIRONMENT_VARIABLES.md
  docs/THIRD_PARTY_SETUP.md
  requirements/base.txt
  scripts/deploy.bash
  scripts/rollbar.bash
  scripts/sentry.bash
Labels: backend, frontend, in progress

#1897 Restructure
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/dashboard/ftux.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/views.py
  app/retail/templates/landing/contributor.html
  app/retail/templates/landing/contributor/gitcoiners.html
  app/retail/templates/landing/funder.html
  app/retail/templates/landing/funder/benefits.html
  app/retail/templates/landing/funder/pilot.html
  app/retail/templates/landing/funder/press.html
  app/retail/templates/ui_inventory.html
  app/retail/views.py
Labels: in progress

#1900 Update the presskit copy
  app/retail/templates/presskit.html
Labels: frontend, in progress

#1894 sends an email to funders who have been inactive for 30 days, asking if they have any feedback
  app/app/urls.py
  app/marketing/mails.py
  app/marketing/management/commands/funder_stale_email.py
  app/retail/emails.py
  scripts/crontab
Labels: in progress

#1911 dashboard: remove tech stack filter
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/shared/sidebar_search.html
Labels: in progress

#1903 Moderators v1
  app/app/settings.py
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/helpers.py
  app/dashboard/management/commands/create_activity_records.py
  app/dashboard/migrations/0100_auto_20180726_1254.py
  app/dashboard/migrations/0101_auto_20180726_1315.py
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/shared/sidebar_search.html
  app/dashboard/tests/test_dashboard_models.py
  app/dashboard/utils.py
  app/dashboard/views.py
  app/git/utils.py
  app/gitcoinbot/tests/test_gitcoinbot_actions.py
  app/marketing/management/commands/expiration_start_work.py
Labels: backend, frontend, in progress

#1924 sync geth stopgap fix
  app/dashboard/management/commands/sync_geth.py
  scripts/crontab
Labels: in progress

#1913 as a user, i want documentation about chain of custody, so that i know my funds are secure
  app/dashboard/templates/bulk_payout_bounty.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/onepager/send2.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/submit_bounty.html
  docs/README.md
Labels: in progress, waiting on contributor

#1927 lander video switcharooooooooooooO
  app/assets/v2/css/landing_page.css
  app/retail/templates/about.html
  app/retail/templates/landing/funder.html
  app/retail/templates/shared/what_is_gitcoin.html
Labels: in progress, needs design

#1916 Confirming Auto-translation
  app/locale/hi/LC_MESSAGES/django.po
  app/locale/hi/LC_MESSAGES/djangojs.po
Labels: enhancement, needs review, translation

#1930 livestream 8/3
  app/retail/emails.py
Labels: in progress

#1931 allow trailing slsah for profile
  app/app/urls.py
Labels: discussion, needs review

#1922 Display project length in issue details page
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: frontend, needs design, needs-testing

#1838 Extend expiration of bounties
  app/app/urls.py
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/extend_issue_deadline.html
  app/dashboard/views.py
Labels: in progress

#1957 what_is_gitcoin : revert to old design
  app/assets/v2/css/landing_page.css
  app/retail/templates/shared/what_is_gitcoin.html
Labels: in progress

#1935 Fix #1934 - Resolve cancelled funds appearing in profile total
  app/dashboard/models.py
Labels: backend, bounties, profile

#1948 bounty: restructure pages
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bounty/fulfill.html
  app/dashboard/templates/bounty/increase.html
  app/dashboard/templates/bounty/kill.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/views.py
Labels: in progress

#1965 workaround for ipfs hashes not existing
  app/dashboard/helpers.py
  app/dashboard/utils.py
Labels: in progress

#1941 explorer: ensure results from latest api call are served to the user
  app/assets/v2/js/pages/dashboard.js
Labels: needs review

#1915 Upgrade django to 2.1, modify field defaults, and address deprecations
  app/app/urls.py
  app/dashboard/models.py
  app/dashboard/views.py
  app/dataviz/models.py
  app/dataviz/templates/cohort.html
  app/dataviz/templates/dataviz/calendar.html
  app/dataviz/templates/dataviz/chord.html
  app/dataviz/templates/dataviz/circles.html
  app/dataviz/templates/dataviz/heatmap.html
  app/dataviz/templates/dataviz/index.html
  app/dataviz/templates/dataviz/spiral.html
  app/dataviz/templates/dataviz/square_graph.html
  app/dataviz/templates/dataviz/steamgraph.html
  app/dataviz/templates/dataviz/sunburst.html
  app/dataviz/templates/funnel.html
  app/dataviz/templates/stats.html
  app/economy/models.py
  app/external_bounties/models.py
  app/faucet/models.py
  app/faucet/templates/process_faucet_request.html
  app/marketing/models.py
  app/retail/templates/admin/index.html
  app/retail/templates/process_accesscode_request.html
  app/retail/templates/resend_tip.html
  app/retail/views.py
  requirements/base.txt
  requirements/test.txt
  setup.cfg
Labels: backend, upgrade

#1971 uri : cleanup
  app/assets/v2/js/pages/dashboard.js
Labels: in progress

#1973 Strip characters from stdbounties_id and check isdigit
  app/app/utils.py
  app/dashboard/views.py
Labels: backend, bounties, in progress

#1975 img: removed unused images
  app/assets/v2/images/about/afj.png
  app/assets/v2/images/about/karot.png
  app/assets/v2/images/about/prserve.jpg
  app/assets/v2/images/avatar_holiday.png
  app/assets/v2/images/colony.png
  app/assets/v2/images/footer.png
  app/assets/v2/images/getgitcoin/find-work.jpg
  app/assets/v2/images/getgitcoin/github.jpg
  app/assets/v2/images/getgitcoin/spaceship.jpg
  app/assets/v2/images/getgitcoin/tip-dev.jpg
  app/assets/v2/images/gitcoin_consensys_dark.jpg
  app/assets/v2/images/tree/ladder.jpg
  app/assets/v2/images/why-different/boulder.jpg
  app/assets/v2/images/why-different/cash.jpg
  app/assets/v2/images/why-different/code_great.jpg
  app/assets/v2/images/why-different/find-work.jpg
  app/assets/v2/images/why-different/heart.jpg
  app/assets/v2/images/why-different/lock.jpg
  app/assets/v2/images/why-different/projects.png
  app/assets/v2/images/why-different/relationships.jpg
  app/assets/v2/images/why-different/search.jpg
  app/assets/v2/images/why-different/search.png
  app/assets/v2/images/why-different/spaceship.jpg
  app/assets/v2/images/why-different/tools 2.jpg
  app/assets/v2/images/why-different/tools.jpg
  app/assets/v2/images/why-different/withdraw.jpg
Labels: in progress

#1984 Newsletter 8/10
  app/retail/emails.py
Labels: in progress

#1841 leaderboard on weekly roundup
  app/retail/emails.py
  app/retail/templates/emails/bounty_roundup.html
Labels: in progress

#1892 Split create_new_bounty kwargs building and check if once
  app/dashboard/helpers.py
  app/economy/models.py
Labels: backend, bounties, in progress

#1856 Minor tweaks to action plan textarea
  app/assets/v2/js/pages/bounty_details.js
Labels: dont merge

#1937 hack: trailing slash for profile
  app/dashboard/views.py
Labels: in progress

#1994 start work : update placeholder
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/addinterest.html
Labels: in progress

#1857 expiration start work day 0
  app/marketing/management/commands/expiration_start_work.py
Labels: in progress

#1963 new bounty : updated UI
  app/assets/v2/css/base.css
  app/assets/v2/css/submit_bounty.css
  app/assets/v2/images/bounty/no_issue.svg
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/bounty/new.html
Labels: in progress

#2006 api: fixed offset param in explorer
  app/dashboard/router.py
Labels: in progress

#2009 Remove FullStory
  app/retail/templates/shared/analytics.html
Labels: frontend, in progress

#2005 bounty: enable accept / reject worker for owner
  app/dashboard/templates/bounty/details.html
Labels: in progress

#1978 Upgrade cryptography python package to 2.3 - Security
  app/dashboard/views.py
  requirements/base.txt
Labels: backend, security, upgrade

#1853 fix it twice for 'why cant i payout this issue?' question for funders
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/details.html
Labels: in progress

#2017 newsletter 8/17
  app/retail/emails.py
Labels: in progress

#2030 refactor: remove unneeded html tag
  app/assets/v2/css/gitcoin.css
  app/retail/templates/landing/contributor/hero.html
  app/retail/templates/shared/hero.html
Labels: frontend

#1998 css: fixes
  app/assets/v2/css/base.css
  app/assets/v2/css/buttons.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/landing_page.css
  app/assets/v2/images/bounty/no_issue.svg
  app/dashboard/templates/bounty/fulfill.html
  app/dashboard/templates/bounty/increase.html
  app/dashboard/templates/bounty/kill.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/bulk_payout_bounty.html
  app/dashboard/templates/process_bounty.html
  app/retail/templates/about.html
Labels: frontend, needs review

#2033 code clean up
  app/dashboard/templates/dashboard/index.html
  app/retail/templates/shared/footer.html
  app/retail/templates/shared/result.html
Labels: in progress

#2027 deprecates old tip receive flow
  app/app/urls.py
  app/assets/onepager/js/quarantine/confetti.js
  app/assets/onepager/js/quarantine/hooked-web3-provider.js
  app/assets/onepager/js/quarantine/index.js
  app/assets/onepager/js/quarantine/lightwallet.min.js
  app/assets/onepager/js/quarantine/pre.js
  app/assets/onepager/js/quarantine/receive_legacy.js
  app/assets/onepager/js/quarantine/tokens.js
  app/assets/onepager/js/quarantine/tx.js
  app/assets/onepager/js/quarantine/web3.js
  app/assets/onepager/js/quarantine/web3alert.js
  app/assets/onepager/js/receive_v2.js
  app/dashboard/models.py
  app/dashboard/templates/onepager/receive_legacy.html
  app/dashboard/templates/onepager/receive_v2.html
  app/dashboard/tip_views.py
Labels: in progress

#2051 refactor: remove save search
  app/app/urls.py
  app/assets/v2/css/base.css
  app/assets/v2/js/base.js
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/dashboard/index.html
  app/dashboard/views.py
  app/retail/templates/save_search.html
Labels: refactor

#2058 dashboard: remove save search link
  app/dashboard/templates/shared/search_bar.html
Labels: in progress

#2048 Use S3 to serve static
  .circleci/config.yml
  app/app/context.py
  app/app/local.env
  app/app/settings.py
  app/app/static_storage.py
  app/app/travis.env
  app/app/urls.py
  app/assets/v2/js/avatar_builder.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/onboard.js
  app/assets/v2/js/shared.js
  app/dashboard/models.py
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bounty/fulfill.html
  app/dashboard/templates/bounty/increase.html
  app/dashboard/templates/bounty/kill.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/bulk_payout_bounty.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/ens/ens_register.html
  app/dashboard/templates/ftux/avatar.html
  app/dashboard/templates/ftux/metamask.html
  app/dashboard/templates/ftux/onboard.html
  app/dashboard/templates/ios.html
  app/dashboard/templates/onepager/send2.html
  app/dashboard/templates/payout_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/profiles/organization.html
  app/dashboard/templates/profiles/profile.html
  app/dashboard/templates/quickstart.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/templates/shared/no_metamask_error.html
  app/dashboard/templates/shared/onepager_auth.html
  app/dashboard/templates/shared/unlock_metamask.html
  app/dashboard/templates/toolbox.html
  app/dashboard/views.py
  app/dataviz/d3_views.py
  app/external_bounties/models.py
  app/external_bounties/templates/external_bounties.html
  app/external_bounties/templates/external_bounties_new.html
  app/external_bounties/templates/external_bounties_show.html
  app/faucet/templates/faucet_form.html
  app/marketing/models.py
  app/retail/templates/emails/bounty_roundup.html
  app/retail/templates/emails/new_match.html
  app/retail/templates/landing/contributor/explorer.html
  app/retail/templates/landing/funder/pilot.html
  app/retail/templates/leaderboard.html
  app/retail/templates/results.html
  app/retail/templates/settings/account.html
  app/retail/templates/settings/tokens.html
  app/retail/templates/shared/activity.html
  app/retail/templates/shared/footer_scripts.html
  js-sdk/src/index.js
  requirements/base.txt
Labels: backend, in progress

#2062 dashboard: enable deep link of search
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/shared/sidebar_search.html
Labels: enhancement, in progress, refactor

#2070 Fixes navbars with dash class, the narrow navbars
  app/assets/v2/css/gitcoin.css
Labels: in progress

#2079 eslint : lint fixes
  app/assets/v2/js/pages/wallet_estimate.js
Labels: in progress

#2076 Update static references to replace hardcoded graph and gas static references
  app/dashboard/templates/ens/base.html
  app/dataviz/templates/dataviz/circles.html
  app/dataviz/templates/dataviz/draggable.html
  app/dataviz/templates/dataviz/heatmap.html
  app/dataviz/templates/dataviz/scatterplot_stripped.html
  app/dataviz/templates/dataviz/spiral.html
  app/dataviz/templates/dataviz/sunburst.html
  app/gas/management/commands/output_gas_viz.py
  app/retail/templates/gas.html
Labels: in progress

#2093 newsletter 8/24
  app/retail/emails.py
Labels: in progress

#2092 Add base elastic apm integration
  app/app/settings.py
  requirements/base.txt
Labels: backend, in progress, performance

#2095 Adds codefund banner in the issue explorer and issue details page
  app/assets/v2/images/codefund_banner.png
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/shared/codefund_banner.html
Labels: in progress

#2105 migrates from current_bounty=True to .current() because the latter is more exhaustive
  app/dashboard/models.py
  app/marketing/management/commands/bounty_feedback_email.py
  app/marketing/management/commands/expiration.py
  app/marketing/management/commands/funder_stale_email.py
  app/marketing/management/commands/new_bounties_email.py
  app/marketing/management/commands/sync_github.py
  app/marketing/utils.py
  app/retail/emails.py
Labels: in progress

#1968 Change Bounty Details
  app/app/urls.py
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/change_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/helpers.py
  app/dashboard/notifications.py
  app/dashboard/templates/bounty/change.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/shared/issue_deadline.html
  app/dashboard/templates/shared/issue_details.html
  app/dashboard/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/bounty_changed.html
  app/retail/templates/emails/bounty_changed.txt
Labels: enhancement

#2107 eslint: fix
  app/assets/v2/js/pages/bounty_details.js
Labels: in progress

#2099 Adds some new eye styles. Male & female versions!
  app/assets/v2/images/avatar/Eyes/5.svg
  app/assets/v2/images/avatar/Eyes/6.svg
  app/avatar/templates/eyes/5.txt
  app/avatar/templates/eyes/6.txt
  app/avatar/utils.py
Labels: frontend

#2109 bounty: crowdfunded bounties
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bulk_payout_bounty.html
  app/dashboard/templates/shared/success_container.html
Labels: in progress

#2123 Fixes version of eth-utils and web3 to make compatible with other pac…
  requirements/base.txt
Labels: dont merge, in progress

#2124 Update text for cookielaw
  app/retail/templates/cookielaw/banner.html
Labels: in progress

#2119 bounty: enable submit only once per user
  app/assets/v2/js/pages/bounty_details.js
Labels: needs review

#2136 newsletter 8/31
  app/retail/emails.py
Labels: in progress
