Repository gitcoinco/web, pull requests merged in 2018-09, with the labels that each got.

#2142 css: fix missing background color
  app/assets/v2/css/landing_page.css
Labels: needs review

#2140 review: added feedback
  app/assets/v2/css/howitworks.css
  app/assets/v2/images/how-it-works/icons/contest.svg
  app/assets/v2/images/how-it-works/icons/cooperative.svg
  app/assets/v2/images/how-it-works/icons/traditional.svg
  app/retail/templates/how_it_works/disputes.html
  app/retail/templates/how_it_works/permissions.html
  app/retail/templates/how_it_works/project_types.html
Labels: frontend

#2131 show accept/reject bounty in permissioned bounty
  app/dashboard/templates/bounty/details.html
Labels: needs review

#2157 Add middleware to disable autodetect lang by header
  app/app/middleware.py
  app/app/settings.py
Labels: backend, in progress, translation

#2111 small tip tweaks
  app/dashboard/admin.py
  app/dashboard/tip_views.py
Labels: in progress

#2146 bounty: changes cancel button to red
  app/assets/v2/css/bounty.css
  app/assets/v2/css/forms/button.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/kill.html
  app/dashboard/templates/shared/no_issue_error.html
Labels: frontend

#2128 landing: reduce size of title on mobile
  app/assets/v2/css/base.css
Labels: in progress

#2161 migrates from current_bounty=True to .current() because the latter is…
  app/dashboard/management/commands/activity_report.py
  app/dashboard/management/commands/create_activity_records.py
  app/dashboard/management/commands/sync_profiles.py
  app/dashboard/notifications.py
  app/dataviz/d3_views.py
  app/economy/management/commands/get_prices.py
  app/economy/management/commands/refresh_bounties.py
  app/external_bounties/management/commands/sync_gitcoin.py
  app/marketing/stats.py
  app/marketing/utils.py
  app/retail/emails.py
Labels: in progress

#1969 Redis based caching
  .circleci/config.yml
  .travis.yml
  app/app/local.env
  app/app/settings.py
  app/app/travis.env
  app/app/utils.py
  app/dashboard/gas_views.py
  app/dashboard/helpers.py
  app/dashboard/management/commands/sync_geth.py
  app/dashboard/notifications.py
  app/dashboard/utils.py
  app/dashboard/views.py
  app/marketing/management/commands/sync_mail.py
  app/retail/utils.py
  app/retail/views.py
  docker-compose.yml
  requirements/base.txt
Labels: backend, in progress

#2162 Refactor issue expiration email
  app/assets/v2/images/cancel.png
  app/assets/v2/images/expiring_clock.png
  app/dashboard/views.py
  app/retail/templates/emails/new_bounty_expire_warning.html
Labels: in progress

#2106 SVG and PNG conversions and handling for Avatars
  Dockerfile
  app/app/urls.py
  app/avatar/admin.py
  app/avatar/apps.py
  app/avatar/exceptions.py
  app/avatar/migrations/0003_auto_20180903_2005.py
  app/avatar/models.py
  app/avatar/templatetags/__init__.py
  app/avatar/templatetags/avatar_tags.py
  app/avatar/utils.py
  app/avatar/views.py
  app/dashboard/models.py
  app/dashboard/templates/profiles/profile.html
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/migrations/0032_leaderboardrank_profile.py
  app/marketing/migrations/0033_auto_20180905_1548.py
  app/marketing/models.py
  app/marketing/views.py
  app/retail/emails.py
  app/retail/templates/emails/bounty_roundup.html
  requirements/base.txt
Labels: avatar, backend, enhancement, needs review

#2138 bot : remove dibs text from message
  app/dashboard/notifications.py
Labels: bot, needs review

#2172 svgo: compress img
  app/assets/v2/images/box.svg
  app/assets/v2/images/close-purple.svg
  app/assets/v2/images/metamask-color.svg
  app/assets/v2/images/quickstart-box.svg
Labels: in progress

#2180 crowdfunded: bug fix
  app/assets/v2/js/pages/bounty_details.js
Labels: in progress

#2181 Roundup email updates for 7SEP2018
  app/retail/emails.py
Labels: emails, in progress

#2133 Cleanup email templates
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/bounty_roundup.html
  app/retail/templates/emails/quarterly_stats.html
  app/retail/templates/emails/shared_bounty_actions.html
  app/retail/templates/emails/template.html
Labels: emails, notifications

#2183 Autogenerated documentation
  .gitignore
  .travis.yml
  app/loader.py
  pydocmd.yml
  requirements/base.txt
Labels: documentation, in progress, wip

#2196 navbar: fix tablet friendly
  app/assets/v2/css/gitcoin.css
  app/retail/templates/shared/nav.html
Labels: in progress

#2202 bot: updated markdown
  app/dashboard/notifications.py
Labels: in progress

#2207 Adjust cookie banner for iOS/Safari
  app/assets/cookielaw/css/cookielaw.css
  app/retail/templates/cookielaw/banner.html
Labels: frontend, mobile, needs review, needs-testing

#2220 hero: updated text + resize + restructure
  app/retail/templates/index.html
  app/retail/templates/landing/contributor/hero.html
  app/retail/templates/landing/funder.html
  app/retail/templates/landing/funder/hero.html
  app/retail/templates/ui_inventory.html
Labels: in progress

#2221 proposed gitcoin contribution monetary policy
  docs/CONTRIBUTING.md
Labels: in progress

#2222 Weekly Roundup - 14SEP2018
  app/retail/emails.py
Labels: emails, needs review

#2236 Update i18n translations and resolve Japanese trans errors
  app/app/settings.py
  app/locale/de/LC_MESSAGES/django.mo
  app/locale/de/LC_MESSAGES/django.po
  app/locale/de/LC_MESSAGES/djangojs.mo
  app/locale/de/LC_MESSAGES/djangojs.po
  app/locale/es/LC_MESSAGES/django.mo
  app/locale/es/LC_MESSAGES/django.po
  app/locale/es/LC_MESSAGES/djangojs.mo
  app/locale/es/LC_MESSAGES/djangojs.po
  app/locale/hi/LC_MESSAGES/django.mo
  app/locale/hi/LC_MESSAGES/django.po
  app/locale/hi/LC_MESSAGES/djangojs.mo
  app/locale/hi/LC_MESSAGES/djangojs.po
  app/locale/it/LC_MESSAGES/django.mo
  app/locale/it/LC_MESSAGES/django.po
  app/locale/it/LC_MESSAGES/djangojs.mo
  app/locale/it/LC_MESSAGES/djangojs.po
  app/locale/ja/LC_MESSAGES/django.mo
  app/locale/ja/LC_MESSAGES/django.po
  app/locale/ja/LC_MESSAGES/djangojs.mo
  app/locale/ja/LC_MESSAGES/djangojs.po
  app/locale/ko/LC_MESSAGES/django.mo
  app/locale/ko/LC_MESSAGES/django.po
  app/locale/ko/LC_MESSAGES/djangojs.mo
  app/locale/ko/LC_MESSAGES/djangojs.po
  app/locale/pl/LC_MESSAGES/django.mo
  app/locale/pl/LC_MESSAGES/django.po
  app/locale/pl/LC_MESSAGES/djangojs.mo
  app/locale/pl/LC_MESSAGES/djangojs.po
  app/locale/zh_Hans/LC_MESSAGES/django.mo
  app/locale/zh_Hans/LC_MESSAGES/django.po
  app/locale/zh_Hans/LC_MESSAGES/djangojs.mo
  app/locale/zh_Hans/LC_MESSAGES/djangojs.po
  app/locale/zh_Hant/LC_MESSAGES/django.mo
  app/locale/zh_Hant/LC_MESSAGES/django.po
  app/locale/zh_Hant/LC_MESSAGES/djangojs.mo
  app/locale/zh_Hant/LC_MESSAGES/djangojs.po
Labels: backend, needs review, translation

#2238 html: updated text on banner contributor page
  app/assets/v2/css/profile.css
  app/retail/templates/landing/contributor/hero.html
Labels: in progress

#2263 Add VSCode remote debugging handling and documentation
  app/manage.py
  bin/docker-command.bash
  docker-compose.yml
  docs/CONTRIBUTING.md
  docs/ENVIRONMENT_VARIABLES.md
Labels: backend, docker, documentation, needs review

#2265 Adjust premailer to use base_url
  app/retail/emails.py
  app/retail/templates/emails/template.html
Labels: backend, bug, emails, in progress

#2264 Update roundup email for 21SEP2018
  app/retail/emails.py
Labels: backend, emails, in progress

#2039 Adds fund branding organisation information with a bounty
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0107_bounty_funding_organisation.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/router.py
  app/dashboard/templates/bounty/new.html
Labels: needs review

#2209 Increase Funding Limit Request Form
  app/app/urls.py
  app/assets/v2/js/pages/increase_funding_limit_request_form.js
  app/dashboard/tip_views.py
  app/marketing/mails.py
  app/retail/forms.py
  app/retail/templates/increase_funding_limit_request_form.html
  app/retail/views.py
Labels: in progress, needs review, needs-testing, wip

#2251 Fix box position bug in select2
  app/assets/v2/js/user-search.js
Labels: frontend, needs review, needs-testing

#2270 updates documentation
  docs/ENVIRONMENT_VARIABLES.md
  docs/THIRD_PARTY_SETUP.md
Labels: in progress

#2274 Makes the issue title a required field in new funding
  app/dashboard/templates/bounty/new.html
Labels: in progress

#1977 Adjust gitcoin bot get_notifications to use pygithub
  app/git/utils.py
  app/gitcoinbot/management/commands/get_notifications.py
Labels: backend, in progress, notifications

#2295 Temporarily removes advanced payout as an option
  app/app/urls.py
  app/dashboard/templates/payout_bounty.html
Labels: in progress

#2298 Update roundup email for 28SEP2018
  app/retail/emails.py
Labels: backend, emails, in progress

#2303 Adjust issue_details to use profile access token
  app/app/pipeline.py
  app/app/utils.py
  app/dashboard/helpers.py
  app/dashboard/models.py
  app/git/utils.py
Labels: backend, bug, in progress, profile

#2304 Adjust issue details token handling and move user specs to currentProfile
  app/app/context.py
  app/app/templates/shared/document_user.html
  app/app/urls.py
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/dashboard/helpers.py
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bounty/new.html
Labels: backend, in progress, profile

#2306 Resolve get_amount 404 on new bounty page
  app/app/templates/shared/current_profile.html
  app/dashboard/helpers.py
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bounty/new.html
Labels: backend, bug, needs review

#2149 WOC: Prevent advanced payout form submission when recipient address is empty
  app/assets/v2/js/pages/bulk_payout.js
Labels: frontend, needs-testing, waiting on contributor, wip
