Repository gitcoinco/web, pull requests merged in 2018-05, with the labels that each got.

#1042 gives staff the ability to remove users from a bounty
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/views.py
Labels: in progress

#1043 fixes https://github.com/gitcoinco/web/issues/1040
  app/dashboard/notifications.py
  app/marketing/management/commands/expiration_start_work.py
Labels: bot, enhancement, mergeable

#1061 css: funding / killing form update
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/form.css
  app/assets/v2/css/forms/input.css
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/submit_bounty.html
Labels: frontend

#809 bounty: unify modal designs
  app/assets/v2/css/forms/button.css
  app/assets/yge/css/main.css
  app/assets/yge/sass/libs/_vars.scss
  app/dashboard/templates/yge/base.html
  app/dashboard/templates/yge/receive.html
  app/dashboard/templates/yge/redeem_coin.html
  app/dashboard/templates/yge/send1.html
  app/dashboard/templates/yge/send2.html
Labels: enhancement, frontend, in progress, needs-testing

#1068 Fixed #1046
  app/assets/v2/js/pages/dashboard.js
Labels: frontend, waiting on contributor

#1055 css: prettified start work dialog box to match style + stop work button
  app/assets/v2/css/bounty.css
  app/dashboard/templates/addinterest.html
  app/dashboard/templates/bounty_details.html
Labels: frontend

#1081 dashboard: fix filter uri
  app/assets/v2/js/pages/dashboard.js
Labels: frontend

#1074 Add left margin for activity time
  app/assets/v2/css/bounty.css
Labels: community member, frontend, waiting on contributor

#1118 updated start work dialog -> to ask hunter for action plan
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/migrations/0070_auto_20180509_1417.py
  app/dashboard/models.py
  app/dashboard/templates/addinterest.html
  app/dashboard/views.py
Labels: needs review

#1114 Style refresh quote button
  app/assets/v2/css/base.css
  app/dashboard/templates/bounty_details.html
Labels: frontend

#1113 Prompt the user to log in before starting work
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/addinterest.html
  app/dashboard/views.py
Labels: waiting on contributor

#1163 about: fixed up CSS for about page community + alumini
  app/assets/v2/css/about.css
  app/assets/v2/images/team/aditya-anand.jpg
  app/retail/templates/community.html
  app/retail/views.py
Labels: ui

#1161 css: added important for overridden prop
  app/assets/v2/css/bounty.css
Labels: needs review, ui

#1164 image: ran make compress-images
  app/assets/v2/images/cancel.png
  app/assets/v2/images/caret-down.png
  app/assets/v2/images/close-grey.png
  app/assets/v2/images/comment.svg
  app/assets/v2/images/dataviz/calendar.png
  app/assets/v2/images/dataviz/chord.png
  app/assets/v2/images/dataviz/circles.png
  app/assets/v2/images/dataviz/graph.png
  app/assets/v2/images/dataviz/heatmap.png
  app/assets/v2/images/dataviz/progression.png
  app/assets/v2/images/dataviz/sankey.png
  app/assets/v2/images/dataviz/scatterplot.png
  app/assets/v2/images/dataviz/spiral.png
  app/assets/v2/images/dataviz/steamgraph.png
  app/assets/v2/images/dataviz/sunburst.png
  app/assets/v2/images/ios/gitcoin.svg
  app/assets/v2/images/ios/iphone_crop.png
  app/assets/v2/images/metamask.svg
  app/assets/v2/images/social/social-icons.svg
Labels: needs review

#1121 js : added gettext across all alerts
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/assets/v2/js/shared.js
  app/assets/v2/js/toolbox.js
  app/assets/yge/redeem_coin.js
  app/assets/yge/youvegoteth/new.js
  app/assets/yge/youvegoteth/receive.js
  app/assets/yge/youvegoteth/send.js
  app/assets/yge/youvegoteth/web3alert.js
Labels: frontend

#1168 bug: added button--primary to back to gitcoin button
  app/assets/yge/youvegoteth/receive.js
Labels: bug, frontend

#1169 Add yapf linting base and lint dataviz app
  Makefile
  app/dataviz/d3_views.py
  app/dataviz/views.py
  requirements/test.txt
  setup.cfg
Labels: backend, enhancement, linting, needs review

#1175 Add CR fixtures and disable get_prices by default
  app/economy/fixtures/initial.json
  app/economy/models.py
  bin/docker-command.bash
  docs/ENVIRONMENT_VARIABLES.md
Labels: backend, docker

#1170 Add fulfillment endpoint for each entry by std bounty id
  app/app/urls.py
  app/dashboard/helpers.py
  app/dashboard/models.py
  app/dashboard/utils.py
  app/dashboard/views.py
Labels: backend, bounties

#1159 css: set limit for image in issue description
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/addinterest.html
Labels: frontend, needs design

#1178 bug: set width to 100% on magnify
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
Labels: bug, ui

#1126 Adds cors headers, and conditionally allow all for GET requests of bounties.
  app/app/settings.py
  app/dashboard/apps.py
  app/dashboard/signals.py
  requirements/base.txt
Labels: backend

#1115 Fixes: https://github.com/gitcoinco/web/issues/1030
  app/assets/v2/css/base.css
  app/assets/v2/js/tokens.js
Labels: in progress

#1150 gitcoinbot: updated language
  app/dashboard/notifications.py
Labels: needs review, needs-testing

#1076 Dynamic widget documentation
  docs/WIDGET.md
  js-sdk/.editorconfig
  js-sdk/.eslintignore
  js-sdk/.eslintrc
  js-sdk/.gitignore
  js-sdk/.npmignore
  js-sdk/.stylelintrc
  js-sdk/README.md
  js-sdk/package.json
  js-sdk/src/index.js
  js-sdk/src/style.css
  js-sdk/webpack.config.js
  js-sdk/yarn.lock
Labels: embedded

#1189 fix for 'accept submission' not showing up
  app/assets/v2/js/pages/bounty_details.js
Labels: in progress

#1195 Modify issueURL placeholder text to reflect GH issues
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/templates/yge/send2.html
Labels: enhancement, frontend, ux improvement

#1187 dashboard : minor fixes
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/tag.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/dashboard.html
Labels: frontend

#1197 css: clean up ENS
  app/assets/v2/css/box_redeem.css
  app/assets/v2/css/external_bounties/checkboxes.css
  app/assets/yge/css/main.css
  app/dashboard/templates/ens/base.html
  app/dashboard/templates/ens/ens.html
  app/dashboard/templates/ens/ens_register.html
  app/dashboard/templates/yge/base.html
Labels: frontend

#1245 GDPR: Remove remembering terms and blockchain tos from the funder forms
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/kill_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/assets/v2/js/tokens.js
Labels: in progress

#1250 GDPR -- Add info to our contact forms
  app/dashboard/templates/shared/newsletter.html
  app/retail/templates/shared/mailchimp.html
Labels: in progress

#1222 GDPR & Associated Privacy Updates -- Must be merged by EOD May 24 2018
  app/app/urls.py
  app/dashboard/templates/legal/privacy.html
  app/dashboard/templates/legal/terms.txt
  app/dashboard/views.py
  app/retail/templates/settings/privacy.html
Labels: to do

#1251 GDPR: show updated policy via modal
  app/assets/v2/css/base.css
  app/assets/v2/css/buttons.css
  app/assets/v2/js/base.js
  app/dashboard/templates/shared/nav_auth.html
Labels: in progress

#1248 GDPR: Adds disclosure and consent withdrawal information in privacy tab
  app/retail/templates/settings/privacy.html
Labels: in progress

#1225 UTS46 ENS domain names
  app/enssubdomain/views.py
Labels: in progress

#1252 GDPR: Management command to send email to all gitcoin users
  app/marketing/mails.py
  app/marketing/management/commands/gdpr_update_email.py
  app/retail/emails.py
  app/retail/templates/emails/gdpr_update.html
  app/retail/templates/emails/gdpr_update.txt
Labels: in progress

#1249 GDPR reconsenet from EU residents
  app/app/urls.py
  app/marketing/mails.py
  app/marketing/management/commands/gdpr_reconsent_eu.py
  app/retail/emails.py
  app/retail/templates/emails/gdpr_reconsent.html
  app/retail/templates/emails/gdpr_reconsent.txt
Labels: in progress

#1254 WIP: GDPR Cookie consent
  app/app/settings.py
  app/assets/cookielaw/css/cookielaw.css
  app/dashboard/templates/ens/base.html
  app/dashboard/templates/yge/base.html
  app/retail/templates/base.html
  app/retail/templates/cookielaw/banner.html
  app/retail/templates/index.html
  app/retail/templates/shared/footer_scripts.html
  app/retail/templates/shared/head.html
  requirements/base.txt
Labels: backend, frontend, in progress

#1247 Email Preferences at a much more granular level
  app/marketing/mails.py
  app/marketing/management/commands/roundup.py
  app/marketing/migrations/0024_auto_20180523_2144.py
  app/marketing/models.py
  app/marketing/tests/test_marketing_utils.py
  app/marketing/utils.py
  app/marketing/views.py
  app/retail/emails.py
  app/retail/templates/settings/email.html
Labels: in progress

#1265 css: update cookie styling
  app/assets/cookielaw/css/cookielaw.css
Labels: frontend, needs review

#1266 settings: updated styling + linting
  app/retail/templates/settings/ens.html
  app/retail/templates/settings/privacy.html
  app/retail/templates/settings/settings.html
Labels: in progress

#1255 settings: redid page
  app/assets/v2/css/base.css
  app/retail/templates/settings/account.html
Labels: in progress

#1146 onboard : autopopulate keywords for users
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/onboard.css
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/_dashboard/ftux.html
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/ftux/github.html
  app/dashboard/templates/ftux/metamask.html
  app/dashboard/templates/ftux/skills.html
  app/dashboard/templates/onboard.html
Labels: core team, needs review

#1269 Updates text in deletion modal
  app/retail/templates/settings/account.html
Labels: in progress

#1260 Mission/Values Page Redesign / Refactor
  app/assets/v2/css/base.css
  app/assets/v2/images/mission/grow_hero.png
  app/assets/v2/images/mission/hero.png
  app/assets/v2/images/mission/interact/1.png
  app/assets/v2/images/mission/interact/10.png
  app/assets/v2/images/mission/interact/2.png
  app/assets/v2/images/mission/interact/3.png
  app/assets/v2/images/mission/interact/4.png
  app/assets/v2/images/mission/interact/5.png
  app/assets/v2/images/mission/interact/6.png
  app/assets/v2/images/mission/interact/7.png
  app/assets/v2/images/mission/interact/8.png
  app/assets/v2/images/mission/interact/9.png
  app/assets/v2/images/mission/interact/book.svg
  app/assets/v2/images/mission/interact/falcon_3.svg
  app/assets/v2/images/mission/interact/goal.svg
  app/assets/v2/images/mission/interact/hammer.svg
  app/assets/v2/images/mission/interact/head.svg
  app/assets/v2/images/mission/interact/hear.svg
  app/assets/v2/images/mission/interact/microscope.svg
  app/assets/v2/images/mission/interact/people_care.svg
  app/assets/v2/images/mission/interact/scale.svg
  app/assets/v2/images/mission/interact/swiss_army.svg
  app/assets/v2/images/mission/interact/world.svg
  app/assets/v2/images/mission/value/collaborative.png
  app/assets/v2/images/mission/value/collaborative.svg
  app/assets/v2/images/mission/value/empathetic.png
  app/assets/v2/images/mission/value/empathetic.svg
  app/assets/v2/images/mission/value/falcon_2.svg
  app/assets/v2/images/mission/value/give-first.png
  app/assets/v2/images/mission/value/give_first.svg
  app/assets/v2/images/mission/value/humble.png
  app/assets/v2/images/mission/value/humble.svg
  app/assets/v2/images/mission/value/inclusive.png
  app/assets/v2/images/mission/value/inclusive.svg
  app/assets/v2/images/mission/value/intellectual-honesty.png
  app/assets/v2/images/mission/value/love_hands.svg
  app/assets/v2/images/mission/value/stress-reducing.png
  app/assets/v2/images/mission/value/stress_reducing.svg
  app/assets/v2/images/mission/want/falcon_1.svg
  app/assets/v2/images/mission/want/financial.png
  app/assets/v2/images/mission/want/find_work.svg
  app/assets/v2/images/mission/want/incentive.svg
  app/assets/v2/images/mission/want/incentives.png
  app/assets/v2/images/mission/want/rocket_man.svg
  app/assets/v2/images/mission/want/work.png
  app/retail/templates/mission.html
Labels: frontend, needs review

#1271 css: fixed font name
  app/assets/v2/_variables.scss
  app/assets/v2/css/base.css
  app/assets/v2/css/carousel.css
  app/assets/v2/css/external_bounties/bounties.css
  app/assets/v2/css/external_bounties/bounty.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/ios.css
  app/assets/yge/css/main.css
Labels: frontend, needs review

#1272 Improves deletion confirmation modal button styling
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/button.css
  app/retail/templates/settings/account.html
Labels: in progress

#1277 Adds SaptakS to team
  app/assets/v2/images/team/saptaks.jpg
  app/retail/views.py
Labels: in progress

#1275 leaderboard updates for mitch
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/migrations/0025_auto_20180525_1943.py
  app/marketing/models.py
  app/marketing/views.py
  app/retail/templates/leaderboard.html
Labels: in progress

#1284 Add checks for bounty/tip notifications on local/dev
  app/dashboard/management/commands/sync_geth.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/utils.py
Labels: in progress

#1299 fixes ENS
  app/enssubdomain/management/__init__.py
  app/enssubdomain/management/commands/__init__.py
  app/enssubdomain/management/commands/reprocess_txs.py
  app/enssubdomain/migrations/0006_enssubdomainregistration_comments.py
  app/enssubdomain/models.py
  app/enssubdomain/views.py
Labels: in progress

#1304 css: fixed dashboard filter row
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/dashboard.html
Labels: frontend, needs review

#1306 Fix: specify height of upper left only for submit bounty form
  app/assets/v2/css/current_balance.css
Labels: in progress

#1281 ftux: refactor + restructure + url rename
  app/app/urls.py
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/ftux/avatar.html
  app/dashboard/templates/ftux/github.html
  app/dashboard/templates/ftux/onboard.html
  app/dashboard/templates/onboard.html
  app/dashboard/views.py
Labels: backend

#1310 org profiles
  app/assets/v2/css/profile.css
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/profile_details.html
Labels: in progress

#1296 adds ENS subdomain registrations to activity report
  app/dashboard/management/commands/activity_report.py
  app/enssubdomain/migrations/0007_enssubdomainregistration_gas_cost_eth.py
  app/enssubdomain/models.py
  app/enssubdomain/views.py
Labels: in progress

#1317 docker-compose was wrong
  docker-compose.yml
Labels: in progress

#1314 Fix primary button style in receive tip success page
  app/assets/yge/youvegoteth/receive.js
Labels: community member, frontend, tips

#1322 show pricing guide on new bounty form
  app/assets/v2/js/amounts.js
Labels: in progress

#1325 toolbox: avoid $.get when url is undefined
  app/assets/v2/js/toolbox.js
Labels: bug, needs review
