Repository gitcoinco/web, pull requests merged in 2018-11, with the labels that each got.

#2662 refactors kudos data profile so the view/data/query is comprehensible
  app/dashboard/models.py
  app/dashboard/views.py
  app/kudos/templates/shared/kudos_card_hover_content.html
  app/kudos/templates/shared/kudos_card_profile.html
Labels: in progress

#2659 Remove range retry attempt from mint_all_kudos
  app/kudos/management/commands/mint_all_kudos.py
Labels: Gitcoin Kudos, backend, in progress

#2677 apply styles just for video modal
  app/assets/v2/css/quickstart.css
Labels: in progress

#2661 Profile fixes
  app/dashboard/views.py
  app/kudos/views.py
Labels: in progress

#2576 Create kudos in feed
  app/app/settings.py
  app/dashboard/migrations/0111_auto_20181101_1922.py
  app/dashboard/models.py
  app/kudos/views.py
  app/marketing/management/commands/assemble_leaderboards.py
  app/retail/templates/shared/activity.html
Labels: in progress

#2530 Issue #2508 Build - Front End of 'No Bounties' Placeholder on Gitcoin…
  app/assets/v2/css/profile.css
  app/assets/v2/images/IssueExplorer.svg
  app/assets/v2/images/Leaderboard.svg
  app/assets/v2/images/Slack.svg
  app/dashboard/models.py
  app/dashboard/templates/profiles/none.html
  app/dashboard/templates/profiles/profile.html
Labels: enhancement, frontend

#2679 Resolve regex deprecation warning in activity_report
  app/dashboard/management/commands/activity_report.py
Labels: backend, needs review

#2466 Adding edited emails.
  app/assets/v2/images/file-text.png
  app/assets/v2/images/update-notification.png
  app/retail/templates/emails/grants/grant_cancellation.html
  app/retail/templates/emails/grants/grant_cancellation.txt
  app/retail/templates/emails/grants/new_supporter.html
  app/retail/templates/emails/grants/new_supporter.txt
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/subscription_terminated.txt
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/support_cancellation.txt
  app/retail/templates/emails/grants/thank_you_for_supporting.html
  app/retail/templates/emails/grants/thank_you_for_supporting.txt
  app/retail/templates/emails/grants/update_notification.html
  app/retail/templates/emails/grants/update_notification.txt
Labels: emails, grants, waiting on contributor

#2697 cleanup stray activities
  app/dashboard/management/commands/cleanup_stray_activities.py
  scripts/crontab
Labels: in progress

#2723 [WIP] Fix email new kudos
  app/kudos/models.py
  app/retail/templates/emails/new_kudos.html
Labels: in progress

#2696 dupe profile cleanup part 2
  app/app/utils.py
  app/dashboard/management/commands/cleanup_dupe_profiles.py
  app/dashboard/views.py
Labels: in progress

#2729 makes profile.handle unique
  app/dashboard/migrations/0112_auto_20181107_2208.py
  app/dashboard/models.py
Labels: Gitcoin Profile, backend

#2734 fixes the logic for avatar save checks
  app/avatar/models.py
Labels: in progress

#2526 Add Contribution model fields
  app/grants/migrations/0002_auto_20181025_1225.py
  app/grants/migrations/0003_contribution_tx_id.py
  app/grants/models.py
Labels: grants, in progress

#2468 Adding transaction summary email.
  app/assets/v2/images/transaction-summary.png
  app/retail/templates/emails/grants/transaction_summary.html
  app/retail/templates/emails/grants/transaction_summary.txt
Labels: emails, grants, waiting on contributor

#2378 WOC: Implement utm* params of a login UserAction stored in the DB feature #2212 #2359
  app/assets/v2/js/base.js
  app/dashboard/migrations/0110_useraction_utm.py
  app/dashboard/models.py
  app/dashboard/tests/test_dashboard_utils.py
  app/dashboard/utils.py
Labels: needs review

#2710 add grants custom nav
  app/assets/v2/images/grants/grants-logo.svg
  app/assets/v2/images/grants/grants-white.gif
  app/dashboard/templates/grants_index.html
  app/retail/templates/shared/footer.html
  app/retail/templates/shared/grants_nav.html
Labels: in progress

#2742 Rinkeby fixes
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/fund_grant.js
  app/assets/v2/js/grants/new.js
  app/grants/models.py
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/views.py
Labels: Gitcoin Grants, in progress

#2522 WIP grants/index: search functionality
  app/app/urls.py
  app/assets/v2/css/grants/grant.css
  app/assets/v2/js/grants/index.js
  app/grants/templates/grants/index.html
  app/grants/urls.py
  app/grants/views.py
Labels: frontend, grants, in progress

#2767 bot: warning -> reminder
  app/dashboard/notifications.py
Labels: Gitcoin Bot, in progress

#2757 Remove full name entry + hide in form.
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/shared/name.html
Labels: enhancement, frontend

#2768 Adjust django logging to output to CW
  app/app/settings.py
  requirements/base.txt
Labels: backend, needs review

#2676 Fix never expires
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
Labels: in progress

#2688 kudos : add share button
  app/assets/v2/css/kudos/styles.css
  app/assets/v2/css/kudos/styles.scss
  app/assets/v2/js/pages/kudos_details.js
  app/kudos/templates/kudos_details.html
  app/kudos/templates/share.html
Labels: Gitcoin Kudos, frontend, in progress

#2769 Add hostfilter for CW logging
  app/app/log_filters.py
  app/app/settings.py
Labels: backend, in progress

#2775 enforce casing / formatting rules for profiles
  app/dashboard/models.py
Labels: in progress

#2766 Profile visuals
  app/assets/v2/css/kudos/styles.css
  app/assets/v2/css/kudos/styles.css.map
  app/assets/v2/css/kudos/styles.scss
  app/dashboard/templates/profiles/profile.html
  app/kudos/templates/shared/kudos_card_hover_content.html
  app/kudos/templates/shared/kudos_card_profile.html
Labels: in progress

#2747 grants: added quickstart + profile placeholder
  app/assets/v2/css/grants/profile.css
  app/assets/v2/css/tabs.css
  app/assets/v2/images/grants/profile/fund.svg
  app/assets/v2/images/grants/profile/start.svg
  app/assets/v2/images/grants/quickstart/fund.svg
  app/assets/v2/images/grants/quickstart/start.svg
  app/assets/v2/js/grants/new.js
  app/grants/templates/grants/profile/body.html
  app/grants/templates/grants/profile/index.html
  app/grants/templates/grants/profile/none.html
  app/grants/templates/grants/quickstart.html
  app/grants/urls.py
  app/grants/views.py
Labels: frontend, grants, in progress

#2799 dont let users submit work unless they've started work
  app/app/pipeline.py
  app/dashboard/models.py
  app/dashboard/views.py
Labels: in progress

#2744 explorer: filters revamp
  app/assets/v2/css/base.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/external_bounties/checkboxes.css
  app/assets/v2/css/forms/input.css
  app/assets/v2/css/forms/radio.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/images/codefund_banner.png
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/dashboard/sidebar_search.html
  app/dashboard/templates/profiles/profile.html
  app/dashboard/templates/shared/codefund_banner.html
  app/dashboard/templates/shared/search_bar.html
  app/dashboard/templates/shared/sidebar_search.html
Labels: frontend, in progress

#2792 update text to state auto-approval after 72 hours doesn't happen
  app/assets/v2/images/how-it-works/icons/timer.svg
  app/retail/templates/emails/start_work_new_applicant.html
  app/retail/templates/how_it_works/permissions.html
Labels: frontend, needs review

#2776 Ks cancel fixes
  app/assets/v2/fonts/muli/muli-v12-latin-200.eot
  app/assets/v2/fonts/muli/muli-v12-latin-200.svg
  app/assets/v2/fonts/muli/muli-v12-latin-200.ttf
  app/assets/v2/fonts/muli/muli-v12-latin-200.woff
  app/assets/v2/fonts/muli/muli-v12-latin-200.woff2
  app/assets/v2/fonts/muli/muli-v12-latin-600.eot
  app/assets/v2/fonts/muli/muli-v12-latin-600.svg
  app/assets/v2/fonts/muli/muli-v12-latin-600.ttf
  app/assets/v2/fonts/muli/muli-v12-latin-600.woff
  app/assets/v2/fonts/muli/muli-v12-latin-600.woff2
  app/assets/v2/fonts/muli/muli-v12-latin-700.eot
  app/assets/v2/fonts/muli/muli-v12-latin-700.svg
  app/assets/v2/fonts/muli/muli-v12-latin-700.ttf
  app/assets/v2/fonts/muli/muli-v12-latin-700.woff
  app/assets/v2/fonts/muli/muli-v12-latin-700.woff2
  app/assets/v2/fonts/muli/muli-v12-latin-regular.eot
  app/assets/v2/fonts/muli/muli-v12-latin-regular.svg
  app/assets/v2/fonts/muli/muli-v12-latin-regular.ttf
  app/assets/v2/fonts/muli/muli-v12-latin-regular.woff
  app/assets/v2/fonts/muli/muli-v12-latin-regular.woff2
  app/assets/v2/js/grants/cancel_subscription.js
  app/dashboard/migrations/0112_auto_20181107_1809.py
  app/grants/migrations/0001_initial.py
  app/grants/templates/grants/cancel.html
Labels: in progress

#2822 Tear down profiles after each test
  app/assets/v2/js/pages/dashboard.js
  app/marketing/tests/management/commands/test_assemble_leaderboards.py
Labels: Gitcoin Profile, backend, bug

#2827 Ks details buttons
  app/grants/templates/grants/detail.html
  app/grants/views.py
Labels: in progress

#2826 Adjust caching for kudos marketplace
  app/app/settings.py
  app/kudos/views.py
Labels: Gitcoin Kudos, backend, in progress

#2806 [WIP]: Email implementation
  app/app/urls.py
  app/assets/v2/js/grants/fund_grant.js
  app/dashboard/migrations/0110_auto_20181027_1727.py
  app/grants/migrations/0001_initial.py
  app/grants/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/new_grant.txt
  app/retail/templates/emails/grants/new_supporter.html
  app/retail/templates/emails/grants/new_supporter.txt
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
Labels: Gitcoin Emails, Gitcoin Grants, in progress

#2829 Remove searchvector usage from kudos marketplace
  app/kudos/migrations/0006_auto_20181114_1854.py
  app/kudos/models.py
  app/kudos/views.py
Labels: Gitcoin Kudos, backend, needs review

#2833 Fix load more kudos card flip
  app/dashboard/templates/profiles/profile.html
Labels: in progress

#2828 qa : fixes
  app/assets/v2/css/forms/form.css
  app/assets/v2/css/forms/input.css
  app/assets/v2/css/forms/label.css
  app/assets/v2/css/grants/detail.css
  app/assets/v2/css/grants/milestones.css
  app/assets/v2/css/grants/new.css
  app/assets/v2/css/tabs.css
  app/assets/v2/js/grants/new.js
  app/grants/forms.py
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/card.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/index.html
  app/grants/templates/grants/milestones.html
  app/grants/templates/grants/nav.html
  app/grants/templates/grants/new.html
  app/grants/templates/grants/profile/index.html
  app/grants/templates/grants/quickstart.html
  app/grants/views.py
Labels: Gitcoin Grants, frontend, in progress

#2703 Fix usd to eth convertion
  app/assets/v2/js/amounts.js
Labels: in progress

#2843 card: clickable + image
  app/assets/v2/css/grants/card.css
  app/assets/v2/css/grants/detail.css
  app/assets/v2/css/grants/grant.css
  app/grants/templates/grants/card.html
  app/grants/templates/grants/detail.html
Labels: Gitcoin Grants, frontend, in progress

#2846 inline -> bulk edit
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/detail.js
  app/grants/templates/grants/detail.html
Labels: Gitcoin Grants, frontend, in progress

#2831 cancel grant functionality implemented
  app/assets/v2/js/grants/compiledSubscriptionContract.js
  app/assets/v2/js/grants/detail.js
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/index.html
  app/grants/views.py
Labels: Gitcoin Grants, in progress

#2839 Explorer popover
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/kudos/styles.css.map
  app/assets/v2/css/tag.css
  app/assets/v2/js/shared.js
  app/dashboard/templates/shared/bounty-popover.html
  app/retail/templates/shared/result.html
Labels: in progress

#2856 grants/card: same size
  app/assets/v2/css/grants/card.css
  app/grants/templates/grants/card.html
Labels: Gitcoin Grants, frontend, in progress

#2849 Ks emails update
  app/app/urls.py
  app/grants/templates/grants/detail.html
  app/grants/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/grants/grant_cancellation.html
  app/retail/templates/emails/grants/subscription_terminated.html
Labels: Gitcoin Emails, Gitcoin Grants, in progress

#2858 fix tooltip not found
  app/assets/v2/js/shared.js
Labels: in progress

#2861 Fix breaking styles
  app/assets/v2/css/dashboard.css
  app/retail/templates/shared/result.html
Labels: in progress

#2880 qa fixes
  app/assets/v2/css/grants/detail.css
  app/assets/v2/css/grants/fund.css
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/templates/grants/quickstart.html
Labels: Gitcoin Grants, Grants QA, in progress

#2881 detail: css fixes
  app/assets/v2/css/grants/detail.css
  app/grants/templates/grants/detail.html
Labels: Gitcoin Grants, in progress

#2876 konami code action update
  app/kudos/templates/kudos_marketplace.html
Labels: in progress

#2567 API: Case-insensitive comparison for is_open
  app/dashboard/router.py
Labels: enhancement

#2336 Fix #2335 - If IPFS_HOST is ipfs pass localhost to IPFSJS
  app/app/context.py
  app/app/settings.py
Labels: backend, bug

#2874 #2746 - Wallpapers being not centered and too small
  app/avatar/utils.py
Labels: Gitcoin Avatar Builder

#2878 Add Makeup category and ziggy-stardust asset to avatar builder #2684
  app/assets/v2/images/avatar/Makeup/ziggy-stardust.svg
  app/assets/v2/js/avatar_builder.js
  app/avatar/templates/makeup/ziggy-stardust.txt
  app/avatar/utils.py
Labels: Gitcoin Avatar Builder

#2896 More QA fixes
  app/assets/v2/css/grants/milestones.css
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/fund_grant.js
  app/grants/forms.py
  app/grants/migrations/0003_auto_20181120_0011.py
  app/grants/migrations/0004_auto_20181120_0027.py
  app/grants/models.py
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/milestones.html
  app/grants/views.py
Labels: Gitcoin Grants, Grants QA, in progress

#2902 More Qa fixes
  app/assets/v2/js/grants/fund_grant.js
  app/assets/v2/js/grants/new.js
  app/grants/models.py
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/views.py
Labels: Gitcoin Grants, Grants QA, in progress

#2910 qa changes
  app/assets/v2/css/grants/card.css
  app/assets/v2/css/grants/grant.css
  app/assets/v2/images/grants/logos/1.png
  app/assets/v2/images/grants/logos/2.png
  app/assets/v2/images/grants/logos/3.png
  app/assets/v2/images/grants/logos/4.png
  app/dashboard/templates/shared/nav_auth.html
  app/grants/templates/grants/card.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/templatetags/grants_extra.py
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
Labels: Gitcoin Grants, Grants QA, in progress

#2915 Fix related profiles alignment
  app/kudos/templates/kudos_details.html
Labels: in progress

#2918 Fix kudos facebook share url
  app/retail/templates/shared/cards_pic.html
Labels: in progress

#2916 Fix activity empty tags
  app/assets/v2/css/activity_stream.css
  app/retail/templates/activity.html
Labels: in progress

#2925 Fix invoice logo
  app/dashboard/templates/bounty/invoice.html
Labels: in progress

#2930 turkey
  app/assets/v2/images/kudos/turkey.svg
  app/kudos/kudos.yaml
Labels: in progress

#2929 Fix #2923 - Adjust handle_worker_approvals to check pending existence
  app/dashboard/views.py
Labels: backend, bug

#2934 Fix wrong profile pic
  app/kudos/templates/shared/kudos_card_profile.html
Labels: in progress

#2673 lookup and sync Kudos/Tips txids success statuses
  app/app/context.py
  app/dashboard/management/commands/activity_report.py
  app/dashboard/management/commands/send_tips_for_bounty_fulfiller.py
  app/dashboard/migrations/0111_auto_20181102_1308.py
  app/dashboard/migrations/0115_merge_20181124_2227.py
  app/dashboard/migrations/0116_auto_20181124_2228.py
  app/dashboard/models.py
  app/dashboard/tip_views.py
  app/dashboard/utils.py
  app/dashboard/views.py
  app/kudos/management/commands/update_tx_status.py
  app/kudos/migrations/0006_auto_20181102_1308.py
  app/kudos/migrations/0007_merge_20181124_2227.py
  app/kudos/migrations/0008_auto_20181124_2228.py
  app/kudos/models.py
  app/kudos/views.py
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/management/commands/expiration_tip.py
  app/marketing/stats.py
  app/retail/utils.py
  scripts/crontab
Labels: in progress

#2941 Fix new grants reverse name in the grants_nav.html
  app/retail/templates/shared/grants_nav.html
Labels: in progress

#2943 Remove the duplicate view and url for grants in dashboard
  app/app/urls.py
  app/assets/v2/js/grants_index.js
  app/dashboard/templates/grants_index.html
  app/dashboard/views.py
  app/retail/templates/shared/grants_nav.html
Labels: in progress

#2921 grant/fund redesign
  app/assets/v2/css/base.css
  app/assets/v2/css/buttons.css
  app/assets/v2/css/forms/input.css
  app/assets/v2/css/grants/fund.css
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/shared.js
  app/assets/v2/js/metamask-approval.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/shared/connect_metamask.html
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
Labels: in progress

#2944 Refactor landing page for grants
  app/assets/v2/css/grants/grant.css
  app/grants/templates/grants/index.html
  app/grants/views.py
Labels: in progress

#2409 dashboard/profile view: performance improvements & refactoring
  app/assets/v2/css/tabs.css
  app/assets/v2/js/pages/profile.js
  app/dashboard/management/commands/create_activity_records.py
  app/dashboard/migrations/0117_auto_20181116_1054.py
  app/dashboard/models.py
  app/dashboard/templates/profiles/profile.html
  app/dashboard/templates/profiles/profile_activities.html
  app/dashboard/templates/shared/profile_activities_bounty.html
  app/dashboard/templates/shared/profile_activities_tip.html
  app/dashboard/tests/test_dashboard_models.py
  app/dashboard/views.py
Labels: enhancement

#2946 grant/cancel-contribute revamp
  app/assets/v2/css/grants/fund.css
  app/assets/v2/images/bitmap.png
  app/assets/v2/images/grants/logos/0.png
  app/assets/v2/images/grants/logos/1.png
  app/assets/v2/images/grants/logos/2.png
  app/assets/v2/images/grants/logos/3.png
  app/assets/v2/images/grants/logos/4.png
  app/grants/templates/grants/banner.html
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/card.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/index.html
  app/retail/templates/emails/grants/new_grant.html
  app/retail/templates/emails/grants/thank_you_for_supporting.html
Labels: Gitcoin Grants, frontend, in progress

#2859 make email sender less aggressive fork udos/tips
  app/dashboard/migrations/0117_tip_primary_email.py
  app/dashboard/migrations/0120_merge_20181126_2232.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/tip_views.py
  app/git/utils.py
  app/kudos/migrations/0008_auto_20181116_1816.py
  app/kudos/migrations/0013_merge_20181126_2232.py
  app/kudos/views.py
  app/marketing/management/commands/sync_mail.py
Labels: in progress

#2302 Fix prodding for unaccepted workers
  app/marketing/management/commands/expiration_start_work.py
  app/marketing/tests/management/commands/test_expiration_start_work.py
Labels: backend, bounties, enhancement

#2903 Kudos suggestions
  app/assets/v2/css/scroll-carousel.css
  app/assets/v2/js/kudos-search.js
  app/assets/v2/js/kudos_suggestions.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/add_kudos.html
Labels: in progress

#2951 Ks contract versioning
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/compiledSubscriptionContract.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/new.js
  app/assets/v2/js/grants/shared.js
  app/dashboard/migrations/0117_merge_20181126_1652.py
  app/grants/migrations/0007_auto_20181126_1652.py
  app/grants/migrations/0008_grant_contract_version.py
  app/grants/models.py
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/detail.html
  app/grants/templates/grants/fund.html
  app/grants/templates/grants/new.html
  app/grants/views.py
Labels: Gitcoin Grants, in progress

#2924 Filter bounties by organization
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/router.py
  app/dashboard/templates/dashboard/sidebar_search.html
  app/dashboard/templates/shared/organization_tooltip.html
Labels: in progress

#2980 Update tip expiration test handling and leaderboard counts
  app/dashboard/models.py
  app/marketing/tests/management/commands/test_assemble_leaderboards.py
  app/marketing/tests/management/commands/test_expiration_tip.py
Labels: Tests, backend, bug

#2981 grantz
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
Labels: in progress

#2979 roundup 11/28
  app/assets/v2/images/kudos/ethergun.svg
  app/assets/v2/images/kudos/helpotron.svg
  app/kudos/kudos.yaml
  app/retail/emails.py
Labels: in progress

#2982 Kevin/mint all kudos hotfix
  app/kudos/management/commands/mint_all_kudos.py
Labels: Gitcoin Kudos, backend, bug

#2976 Flash Mask and Eye Patch Accessory
  app/assets/v2/images/avatar/Accessories/Masks-eye-patch.svg
  app/assets/v2/images/avatar/Accessories/Masks-flash.svg
  app/avatar/templates/accessories/masks/eye-patch.txt
  app/avatar/templates/accessories/masks/flash.txt
  app/avatar/utils.py
Labels: avatars, backend, frontend

#2985 Accessory - Wolverine Mask
  app/assets/v2/images/avatar/Accessories/Masks-wolverine.svg
  app/avatar/templates/accessories/masks/wolverine.txt
  app/avatar/utils.py
Labels: avatars, backend, frontend

#2992 fixes web3 functionality on grantz
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/shared.js
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/index.html
  app/grants/templates/grants/new.html
Labels: Gitcoin Grants, frontend

#2991 primary email was wrong type
  app/dashboard/tip_views.py
  app/kudos/views.py
Labels: in progress

#2990 new bottom notification
  app/retail/templates/shared/bottom_notification.html
Labels: in progress

#2996 Fix issuel URL in grants cancel cb
  app/assets/v2/js/grants/detail.js
Labels: in progress

#2997 qa+ corner cases
  app/assets/v2/css/grants/grant.css
  app/assets/v2/images/grants/icons/black.svg
  app/assets/v2/images/grants/icons/white.svg
  app/assets/v2/images/shrug_bot.png
  app/dashboard/templates/shared/nav_auth.html
  app/grants/templates/grants/index.html
  app/grants/templates/grants/quickstart.html
  app/grants/templates/grants/shared/error.html
  app/grants/templates/grants/stub/index.html
  app/grants/views.py
Labels: in progress

#3000 Handle raised exceptions from profile_helper
  app/dashboard/views.py
  app/marketing/management/commands/pull_github.py
Labels: Gitcoin Profile, backend, bug, in progress

#3006 updated the grant error page
  app/assets/v2/images/obiwan-bot.svg
  app/grants/templates/grants/shared/error.html
Labels: in progress

#3004 Accessory - santa moustache and beard
  app/assets/v2/images/avatar/Accessories/Extras-santa.svg
  app/avatar/templates/accessories/extras/santa.txt
  app/avatar/utils.py
Labels: avatars, frontend

#3024 updated the grant error page
  app/assets/v2/js/grants/shared.js
Labels: in progress

#3009 Add pagination to grants with style
  app/assets/v2/js/infinite.min.js
  app/assets/v2/js/jquery.waypoints.min.js
  app/grants/templates/grants/index.html
  app/grants/views.py
Labels: Gitcoin Grants, enhancement, frontend

#3025 Migrate to alpine 3.8 image base
  Dockerfile
  Makefile
  docker-compose.yml
  ops/images/job/Dockerfile
  ops/images/kubectl/Dockerfile
  requirements/test.txt
Labels: backend, docker, enhancement, needs review

#3012 Ks grantz details edit update
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/new.js
  app/grants/migrations/0002_update.py
  app/grants/models.py
  app/grants/templates/grants/detail.html
  app/grants/views.py
Labels: Gitcoin Grants, in progress

#3029 qa fixes
  app/assets/v2/js/grants/shared.js
  app/grants/templates/grants/card.html
  app/grants/templates/grants/shared/alpha.html
Labels: in progress

#3031 runserver verbosity to 0
  bin/docker-command.bash
Labels: in progress

#2995 Add cancel modal on cancelling grants
  app/assets/v2/css/grants/detail.css
  app/assets/v2/images/grants/cancel-grants-icon.png
  app/assets/v2/js/grants/detail.js
  app/grants/templates/grants/detail.html
Labels: Gitcoin Grants, frontend

#2968 Fix #2746 - Makeup causing issues aswell
  app/avatar/utils.py
Labels: needs review, needs-testing

#3033 fix fund reject issue
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/new.js
  app/grants/templates/grants/cancel.html
Labels: in progress

#3036 updated grant check in url to path name
  app/assets/v2/js/shared.js
Labels: in progress
