Repository gitcoinco/web, pull requests merged in 2018-04, with the labels that each got.

#757 bounty: css letter spacing fix for h1..h6
  app/assets/v2/css/bounty.css
Labels: frontend

#735 #679 - new issue responsive updates
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/form.css
  app/dashboard/templates/shared/bounty_nav.html
  app/dashboard/templates/submit_bounty.html
Labels: frontend

#771 disable my projects filters if user not logged in
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/shared/sidebar_search.html
Labels: frontend, needs review, waiting on contributor

#758 Alpha Tag
  app/assets/v2/css/base.css
  app/assets/yge/css/main.css
  app/dashboard/templates/profile_details.html
  app/faucet/templates/faucet_form.html
  app/retail/templates/gas.html
  app/retail/templates/leaderboard.html
Labels: frontend, needs review

#785 explorer: updated label for issues with status done
  app/assets/v2/js/pages/dashboard.js
Labels: needs design, needs review

#775 CSS clean up 🎉
  .editorconfig
  .stylelintrc
  app/assets/v2/css/animate.min.css
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/buttons.css
  app/assets/v2/css/card.css
  app/assets/v2/css/carousel.css
  app/assets/v2/css/current_balance.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/external_bounties/bounties.css
  app/assets/v2/css/external_bounties/bounty.css
  app/assets/v2/css/external_bounties/checkboxes.css
  app/assets/v2/css/faucet.css
  app/assets/v2/css/forms/checkbox.css
  app/assets/v2/css/forms/form.css
  app/assets/v2/css/forms/input.css
  app/assets/v2/css/forms/label.css
  app/assets/v2/css/forms/radio.css
  app/assets/v2/css/forms/select.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/help.css
  app/assets/v2/css/ios.css
  app/assets/v2/css/jquery-ui.css
  app/assets/v2/css/leaderboard.css
  app/assets/v2/css/newsletter.css
  app/assets/v2/css/rain.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/css/timeline.css
  app/assets/v2/css/toolbox.css
  app/assets/v2/fonts/Muli/Bold.ttf
  app/assets/v2/fonts/Muli/BoldItalic.ttf
  app/assets/v2/fonts/Muli/ExtraLight.ttf
  app/assets/v2/fonts/Muli/ExtraLightItalic.ttf
  app/assets/v2/fonts/Muli/Light.ttf
  app/assets/v2/fonts/Muli/LightItalic.ttf
  app/assets/v2/fonts/Muli/Regular.ttf
  app/assets/v2/fonts/Muli/RegularItalic.ttf
  app/assets/v2/fonts/Muli/SemiBold.ttf
  app/assets/v2/fonts/Muli/SemiBoldItalic.ttf
  app/assets/yge/css/ie8.css
  app/assets/yge/css/ie9.css
  app/assets/yge/css/main.css
  app/assets/yge/css/main.print.css
  app/assets/yge/css/noscript.css
  package-lock.json
Labels: frontend, linting, mergeable, needs review

#791 Limit Profile stat results to valid bounties
  Makefile
  app/dashboard/embed.py
  app/dashboard/migrations/0050_auto_20180404_1109.py
  app/dashboard/models.py
  app/dashboard/router.py
Labels: backend, bounties, needs review, profile

#574 Add django auth framework
  app/app/context.py
  app/app/pipeline.py
  app/app/settings.py
  app/app/tests/test_app_urls.py
  app/app/urls.py
  app/app/utils.py
  app/dashboard/migrations/0051_auto_20180405_0806.py
  app/dashboard/models.py
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/tests/test_tokens.py
  app/dashboard/views.py
  app/faucet/templates/faucet_form.html
  app/github/middleware.py
  app/github/tests/test_utils.py
  app/github/utils.py
  app/github/views.py
  app/marketing/views.py
  requirements/base.txt
  scripts/crontab
Labels: backend, in progress, needs review, needs-testing, profile, user

#768 bounty : minor changes
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/bounty_details.html
Labels: frontend, in progress, needs design

#784 bounty: fixed avatar url + tooltip style
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: frontend, needs design, needs review

#818 Django auth
  app/app/context.py
  app/app/pipeline.py
  app/app/settings.py
  app/app/tests/test_app_urls.py
  app/app/urls.py
  app/app/utils.py
  app/dashboard/migrations/0051_auto_20180405_0806.py
  app/dashboard/models.py
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/tests/test_tokens.py
  app/dashboard/utils.py
  app/dashboard/views.py
  app/external_bounties/views.py
  app/faucet/templates/faucet_form.html
  app/faucet/views.py
  app/github/middleware.py
  app/github/tests/test_utils.py
  app/github/utils.py
  app/github/views.py
  app/marketing/views.py
  requirements/base.txt
  scripts/crontab
Labels: in progress

#821 todos should be falsy
  app/app/settings.py
Labels: in progress

#762 bounty: mobile alignment fix
  app/assets/v2/css/bounty.css
Labels: frontend, mobile

#764 bounty: added progress bar
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: frontend, needs design, needs review

#828 bounty: hide progress bar on work done status
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: frontend

#827 Fixes: https://github.com/gitcoinco/web/issues/792
  app/assets/v2/css/base.css
  app/dashboard/templates/profile_details.html
Labels: frontend, profile

#746 Email design update
  app/app/urls.py
  app/assets/v2/images/grow_open_source_new.png
  app/assets/v2/images/social/facebook_new.png
  app/assets/v2/images/social/medium_new.png
  app/assets/v2/images/social/reddit_new.png
  app/assets/v2/images/social/slack_new.png
  app/assets/v2/images/social/twitter_new.png
  app/retail/emails.py
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/bounty_roundup.html
  app/retail/templates/emails/bounty_roundup.txt
  app/retail/templates/emails/bounty_startwork_expire_warning.html
  app/retail/templates/emails/bounty_startwork_expire_warning.txt
  app/retail/templates/emails/faucet_request.html
  app/retail/templates/emails/faucet_request_rejected.html
  app/retail/templates/emails/new_bounty.html
  app/retail/templates/emails/new_bounty.txt
  app/retail/templates/emails/new_bounty_acceptance.html
  app/retail/templates/emails/new_bounty_expire_warning.html
  app/retail/templates/emails/new_bounty_expire_warning.txt
  app/retail/templates/emails/new_bounty_rejection.html
  app/retail/templates/emails/new_bounty_rejection.txt
  app/retail/templates/emails/new_match.html
  app/retail/templates/emails/new_match.txt
  app/retail/templates/emails/new_tip.html
  app/retail/templates/emails/new_tip.txt
  app/retail/templates/emails/new_work_submission.html
  app/retail/templates/emails/new_work_submission.txt
  app/retail/templates/emails/render_bounty_startwork_expired.html
  app/retail/templates/emails/render_bounty_startwork_expired.txt
  app/retail/templates/emails/template.html
Labels: emails, in progress, needs review, needs-testing

#825 responsive profile
  app/assets/v2/css/base.css
  app/dashboard/templates/profile_details.html
Labels: enhancement, frontend, profile

#840 fix for Expired bounty invalid days ago counter
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: bounties, frontend, in progress, mergeable

#861 docker shell fixes
  bin/docker-command.bash
  docker-compose.yml
  docs/RUNNING_LOCALLY_DOCKER.md
Labels: in progress

#863 Add ipdb and django shell access to docker setup
  Makefile
  docker-compose.yml
  docs/RUNNING_LOCALLY_DOCKER.md
Labels: backend, docker, documentation, in progress

#862 Django Auth Redux
  app/app/context.py
  app/app/pipeline.py
  app/app/settings.py
  app/app/tests/test_app_urls.py
  app/app/urls.py
  app/app/utils.py
  app/dashboard/ios.py
  app/dashboard/migrations/0051_auto_20180405_0806.py
  app/dashboard/models.py
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/tests/test_tokens.py
  app/dashboard/utils.py
  app/dashboard/views.py
  app/external_bounties/views.py
  app/faucet/templates/faucet_form.html
  app/faucet/views.py
  app/github/middleware.py
  app/github/tests/test_utils.py
  app/github/utils.py
  app/github/views.py
  app/marketing/mails.py
  app/marketing/management/commands/ingest_slack_users.py
  app/marketing/migrations/0021_emailsubscriber_profile.py
  app/marketing/models.py
  app/marketing/tests/test_marketing_utils.py
  app/marketing/utils.py
  app/marketing/views.py
  app/retail/templates/email_settings.html
  requirements/base.txt
  scripts/crontab
Labels: backend, emails, profile

#853 Feature/refactor value in usdt
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/embed.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/router.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/profile_details.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/tests/test_dashboard_models.py
  app/economy/management/commands/get_prices.py
  app/economy/tests/test_economy_utils.py
  app/economy/utils.py
  app/marketing/mails.py
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/management/commands/pull_stats.py
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/bounty.txt
  docs/API.md
  requirements/base.txt
Labels: backend, enhancement, frontend, needs review, needs-testing

#878 status update dates on the bounty model
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0052_auto_20180413_0736.py
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/bounty_details.html
  app/marketing/management/commands/bounty_feedback_email.py
  app/marketing/management/commands/pull_stats.py
  scripts/restore_backup.bash
Labels: bounties, in progress, mergeable

#881 new nav for auth/login for site
  app/assets/v2/css/base.css
  app/dashboard/templates/shared/nav_auth.html
  app/retail/templates/shared/nav.html
Labels: in progress

#745 in my settings, i should be able to disguise myself from the leaderboard/having a profile
  app/app/urls.py
  app/dashboard/migrations/0051_profile_suppress_leaderboard.py
  app/dashboard/migrations/0053_merge_20180413_0755.py
  app/dashboard/models.py
  app/dashboard/templates/shared/nav_auth.html
  app/economy/management/commands/get_prices.py
  app/marketing/mails.py
  app/marketing/management/commands/assemble_leaderboards.py
  app/marketing/views.py
  app/retail/templates/email_settings.html
  app/retail/templates/settings/email.html
  app/retail/templates/settings/feedback.html
  app/retail/templates/settings/matching.html
  app/retail/templates/settings/privacy.html
  app/retail/templates/settings/settings.html
Labels: backend, frontend

#867 new_bounty emails
  app/dashboard/notifications.py
  app/marketing/mails.py
  app/marketing/management/commands/new_bounties_email.py
  app/marketing/management/commands/send_subscription_mails.py
  app/retail/emails.py
  app/retail/templates/emails/new_bounty.html
  app/retail/templates/emails/new_bounty.txt
  scripts/crontab
Labels: in progress

#882 identify trust wallet
  app/assets/v2/js/pages/wallet_estimate.js
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/wallet_estimate.html
  app/dashboard/templates/submit_bounty.html
Labels: frontend, needs review, needs-testing

#885 Update Travis pipeline to use new stages
  .travis.yml
Labels: devops, docker, in progress, travis

#458 Detect GitHub issue activity other than comments
  app/github/tests/test_utils.py
  app/github/utils.py
  app/marketing/management/commands/expiration_start_work.py
  app/marketing/tests/management/commands/test_expiration_start_work.py
  app/marketing/tests/management/commands/test_expiration_tip.py
Labels: backend, enhancement, needs review, needs-testing

#897 Github comments when user is warned/removed (in addition to the emails that are sent when this happens)
  app/dashboard/notifications.py
  app/marketing/management/commands/expiration_start_work.py
Labels: in progress

#899 Add admin link to navbar for staff and switch settings icon
  app/dashboard/templates/shared/nav_auth.html
Labels: frontend, ui

#898 adds tutorials on help page
  app/assets/v2/css/base.css
  app/assets/v2/images/help/firehose.jpg
  app/assets/v2/images/help/tools.png
  app/retail/templates/help.html
  app/retail/views.py
Labels: frontend

#887 Added team bios and community member links to /about page
  app/assets/v2/css/about.css
  app/assets/v2/images/social/gitcoin.png
  app/assets/v2/images/team/alisa-march.jpg
  app/assets/v2/images/team/eric-berry.jpg
  app/assets/v2/images/team/justin-bean.jpg
  app/assets/v2/images/team/kevin-owocki.png
  app/assets/v2/images/team/mark-beacom.jpg
  app/assets/v2/images/team/vivek-singh.jpg
  app/retail/templates/about.html
  app/retail/views.py
  app/static/v2/images/social/gitcoin.png
  package-lock.json
Labels: frontend, waiting on contributor

#890 nav + explorer fixes
  app/assets/v2/css/base.css
  app/assets/v2/css/search_bar.css
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/shared/nav_auth.html
Labels: dashboard, frontend, mergeable, needs design, ui

#904 navbar responsive issues
  app/retail/templates/shared/nav.html
Labels: frontend, needs design

#902 avatar cleanup - and adds the ability to blend in the gitcoin logo to an avatar
  app/app/urls.py
  app/dashboard/embed.py
  app/dashboard/helpers.py
  app/dashboard/migrations/0055_remove_bounty_avatar_url.py
  app/dashboard/models.py
  app/dashboard/templates/profile_details.html
  app/dashboard/tests/test_dashboard_models.py
  app/dashboard/views.py
  app/economy/management/commands/refresh_bounties.py
  app/marketing/models.py
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/new_match.html
  app/retail/templates/leaderboard.html
  requirements/base.txt
Labels: in progress

#913 expiration tests fix
  app/marketing/tests/management/commands/test_expiration_start_work.py
Labels: bug, tests

#918 make expiration status less inclusive
  app/dashboard/models.py
  app/dashboard/tests/test_dashboard_models.py
Labels: in progress

#919 fixes https://github.com/gitcoinco/web/issues/876
  app/app/settings.py
Labels: in progress

#763 Tool voting
  app/app/tests/test_app_urls.py
  app/app/urls.py
  app/assets/v2/css/card.css
  app/assets/v2/css/toolbox.css
  app/assets/v2/js/toolbox.js
  app/dashboard/embed.py
  app/dashboard/migrations/0056_auto_20180419_0910.py
  app/dashboard/migrations/0057_auto_20180419_0910.py
  app/dashboard/models.py
  app/dashboard/templates/toolbox.html
  app/dashboard/tests/test_dashboard_models.py
  app/dashboard/views.py
Labels: backend, feature, frontend

#933 about: Fix Origin Story
  app/assets/v2/css/about.css
  app/assets/v2/css/base.css
  app/retail/templates/about.html
Labels: frontend

#942 track hours worked on fulfillment
  app/assets/v2/js/pages/fulfill_bounty.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0058_auto_20180423_1746.py
  app/dashboard/models.py
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/shared/hours_worked.html
Labels: in progress

#944 Tool modifications
  app/app/utils.py
  app/dashboard/migrations/0057_auto_20180419_0910.py
  app/dashboard/migrations/0060_tool_modifications.py
  app/dashboard/models.py
  app/dashboard/templates/toolbox.html
  app/dashboard/views.py
Labels: backend, in progress

#930 more feedback emails
  app/marketing/mails.py
  app/marketing/management/commands/bounty_feedback_email.py
  app/retail/emails.py
Labels: in progress, mergeable

#956 Adds bounty flow doc to readme
  docs/README.md
  docs/bounty_flow.png
Labels: in progress

#810 preferred language
  app/app/pipeline.py
  app/app/settings.py
  app/app/utils.py
  app/dashboard/migrations/0061_profile_pref_lang_code.py
  app/dashboard/models.py
  app/marketing/mails.py
  app/marketing/views.py
  app/retail/templates/settings/email.html
  app/tdi/views.py
Labels: emails, frontend, in progress, mergeable, translation

#931 verboseness of gitcoinbot reminders
  app/dashboard/notifications.py
  app/marketing/management/commands/expiration_start_work.py
Labels: in progress

#948 smarter github notifications
  app/dashboard/notifications.py
  app/marketing/management/commands/expiration_start_work.py
Labels: in progress

#977 warnings when youre looking at a non mainnet bounty
  app/assets/v2/css/bounty.css
  app/assets/v2/css/tag.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/dashboard.html
Labels: frontend, in progress

#980 Modify setup_lang to use User
  app/dashboard/models.py
  app/marketing/mails.py
  app/marketing/tests/test_mails.py
Labels: backend, bug, emails, in progress, translation

#983 Action URLS Cleanup (and other goodies)
  app/app/urls.py
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/kill_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/assets/v2/js/shared.js
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/bounty_actions_hidden_vars.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/views.py
  app/legacy/urls.py
  docs/API.md
Labels: in progress

#888 Upgrade deb image to Stretch
  Dockerfile
  requirements/base.txt
  requirements/test.txt
Labels: docker, in progress, upgrade

#955 Add slack bot integration
  app/app/urls.py
  app/dashboard/helpers.py
  app/dashboard/models.py
  app/dashboard/notifications.py
  app/dashboard/views.py
  app/marketing/views.py
  app/retail/templates/settings/slack.html
Labels: bot

#998 adds rates estimate on bounty details page
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: in progress

#790 Initial commit for Search functionality
  app/assets/v2/css/base.css
  app/assets/v2/css/bootstrap.min.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/images/caret-down.png
  app/assets/v2/images/close-grey.png
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/shared/search_bar.html
  app/dashboard/templates/shared/sidebar_search.html
  app/dashboard/templates/yge/base.html
Labels: frontend, in progress

#886 WIP - d3 data viz experiments
  .eslintignore
  app/app/settings.py
  app/app/tests/test_app_urls.py
  app/app/urls.py
  app/assets/v2/images/dataviz/calendar.png
  app/assets/v2/images/dataviz/chord.png
  app/assets/v2/images/dataviz/circles.png
  app/assets/v2/images/dataviz/graph.png
  app/assets/v2/images/dataviz/heatmap.png
  app/assets/v2/images/dataviz/progression.png
  app/assets/v2/images/dataviz/sankey.png
  app/assets/v2/images/dataviz/scatterplot.png
  app/assets/v2/images/dataviz/spiral.png
  app/assets/v2/images/dataviz/steamgraph.png
  app/assets/v2/images/dataviz/sunburst.png
  app/assets/v2/js/dataviz/d3.v3.js
  app/assets/v2/js/dataviz/dragit.css
  app/assets/v2/js/dataviz/dragit.js
  app/assets/v2/js/dataviz/heatmap.css
  app/assets/v2/js/dataviz/heatmap.js
  app/assets/v2/js/dataviz/sequences.css
  app/assets/v2/js/dataviz/sequences.js
  app/assets/v2/js/dataviz/spiral.js
  app/dashboard/models.py
  app/dataviz/__init__.py
  app/dataviz/admin.py
  app/dataviz/apps.py
  app/dataviz/d3_views.py
  app/dataviz/migrations/0001_initial.py
  app/dataviz/migrations/__init__.py
  app/dataviz/models.py
  app/dataviz/templates/cohort.html
  app/dataviz/templates/dataviz/calendar.html
  app/dataviz/templates/dataviz/chord.html
  app/dataviz/templates/dataviz/circles.html
  app/dataviz/templates/dataviz/draggable.html
  app/dataviz/templates/dataviz/graph.html
  app/dataviz/templates/dataviz/heatmap.html
  app/dataviz/templates/dataviz/index.html
  app/dataviz/templates/dataviz/scatterplot.html
  app/dataviz/templates/dataviz/shared/nav.html
  app/dataviz/templates/dataviz/spiral.html
  app/dataviz/templates/dataviz/square_graph.html
  app/dataviz/templates/dataviz/steamgraph.html
  app/dataviz/templates/dataviz/sunburst.html
  app/dataviz/templates/funnel.html
  app/dataviz/templates/stats.html
  app/dataviz/views.py
  app/marketing/models.py
  app/marketing/views.py
  app/retail/templates/admin/index.html
Labels: in progress

#884 WIP: Update FaucetRequest with FK to Profile
  app/dashboard/models.py
  app/dataviz/migrations/0002_auto_20180430_1914.py
  app/faucet/admin.py
  app/faucet/migrations/0008_faucetrequest_profile.py
  app/faucet/migrations/0009_auto_20180413_0725.py
  app/faucet/migrations/0010_auto_20180430_1914.py
  app/faucet/models.py
  app/faucet/templates/faucet_form.html
  app/faucet/views.py
  app/github/utils.py
  app/retail/emails.py
Labels: faucet, in progress, needs-testing, wip

#936 sets default search project status to 'any'
  app/dashboard/templates/shared/sidebar_search.html
Labels: frontend, in progress, mergeable

#889 ftux: birth
  .stylelintrc
  app/app/urls.py
  app/assets/v2/css/base.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/onboard.css
  app/assets/v2/images/metamask.svg
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/dashboard.html
  app/dashboard/templates/onboard.html
  app/dashboard/views.py
Labels: backend, frontend, ftux, in progress, needs review, needs-testing
