Repository gitcoinco/web, pull requests merged in 2018-06, with the labels that each got.

#1328 Decrease the scope of GH perms requested on login
  app/app/settings.py
Labels: backend, in progress

#1335 Adjust sync_geth settings and docs for local
  app/dashboard/management/commands/sync_geth.py
  docs/RUNNING_LOCALLY.md
  docs/RUNNING_LOCALLY_DOCKER.md
  scripts/crontab
Labels: backend, bounties, in progress

#1339 disable sendgrid events until we figure out root cause of db size issues
  app/marketing/webhookviews.py
Labels: in progress

#1333 fontawesome: revert to css
  app/assets/v2/css/about.css
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/carousel.css
  app/assets/v2/css/current_balance.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/external_bounties/bounties.css
  app/assets/v2/css/external_bounties/bounty.css
  app/assets/v2/css/fontawesome-all.min.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/newsletter.css
  app/assets/v2/css/onboard.css
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/js/fontawesome-all.min.js
  app/assets/v2/js/pages/onboard.js
  app/assets/v2/webfonts/fa-brands-400.eot
  app/assets/v2/webfonts/fa-brands-400.svg
  app/assets/v2/webfonts/fa-brands-400.ttf
  app/assets/v2/webfonts/fa-brands-400.woff
  app/assets/v2/webfonts/fa-brands-400.woff2
  app/assets/v2/webfonts/fa-regular-400.eot
  app/assets/v2/webfonts/fa-regular-400.svg
  app/assets/v2/webfonts/fa-regular-400.ttf
  app/assets/v2/webfonts/fa-regular-400.woff
  app/assets/v2/webfonts/fa-regular-400.woff2
  app/assets/v2/webfonts/fa-solid-900.eot
  app/assets/v2/webfonts/fa-solid-900.svg
  app/assets/v2/webfonts/fa-solid-900.ttf
  app/assets/v2/webfonts/fa-solid-900.woff
  app/assets/v2/webfonts/fa-solid-900.woff2
  app/dashboard/templates/shared/yge_auth.html
  app/retail/templates/results.html
  app/retail/templates/shared/head.html
Labels: frontend, needs review

#1338 Trim issue action plan before validation
  app/assets/v2/js/pages/bounty_details.js
Labels: frontend

#1346 temp: using font-awesome CDN
  app/dashboard/templates/shared/yge_auth.html
  app/retail/templates/shared/head.html
Labels: in progress

#1354 Fix font awesome icon classes
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/bounty_details.html
Labels: bug, frontend

#1360 Fix FontAwesome static refs
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/ens/base.html
  app/dashboard/templates/shared/current_balance.html
  app/dashboard/templates/shared/search_bar.html
  app/dashboard/templates/shared/yge_auth.html
  app/dashboard/templates/yge/base.html
  app/dataviz/templates/cohort.html
  app/dataviz/templates/dataviz/circles.html
  app/dataviz/templates/dataviz/draggable.html
  app/dataviz/templates/dataviz/graph.html
  app/dataviz/templates/dataviz/heatmap.html
  app/dataviz/templates/dataviz/index.html
  app/dataviz/templates/dataviz/spiral.html
  app/dataviz/templates/dataviz/steamgraph.html
  app/dataviz/templates/dataviz/sunburst.html
  app/dataviz/templates/funnel.html
  app/dataviz/templates/stats.html
  app/external_bounties/templates/external_bounties_show.html
  app/faucet/templates/process_faucet_request.html
  app/retail/templates/admin/index.html
  app/retail/templates/leaderboard.html
  app/retail/templates/process_accesscode_request.html
  app/retail/templates/resend_tip.html
  app/retail/templates/shared/head.html
Labels: frontend, in progress

#1384 Enhancement bounty info view on the bounty details page
  app/assets/v2/css/bounty.css
Labels: in progress

#1381 Clean hashbang from gh urls
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/helpers.py
  app/dashboard/models.py
  app/dashboard/tests/test_dashboard_models.py
  app/dashboard/tests/test_dashboard_utils.py
  app/dashboard/utils.py
  app/dashboard/views.py
Labels: backend, bug, needs review

#1365 Update top banners in different bounty flow pages
  app/assets/v2/css/base.css
  app/assets/v2/images/box.svg
  app/assets/v2/images/refund.svg
  app/assets/v2/js/shared.js
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/no_issue_error.html
  app/dashboard/templates/shared/unlock_metamask.html
  app/dashboard/templates/shared/zero_balance_error.html
  app/dashboard/templates/submit_bounty.html
Labels: frontend, in progress, needs-testing

#1342 profile : revamp
  app/assets/v2/css/base.css
  app/assets/v2/css/dashboard.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/profile.css
  app/dashboard/templates/profile_details.html
  app/dashboard/templates/shared/profile_activities_bounty.html
  app/retail/templates/shared/result.html
Labels: frontend

#1332 shared: refactored + removed dead code
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
Labels: frontend, needs review

#1396 Corrects lightbulb image name
  app/dashboard/templates/shared/no_issue_error.html
Labels: in progress

#1397 Adds funding link in the navbar for landing page
  app/retail/templates/shared/nav.html
Labels: in progress

#1392 Fixes: https://github.com/gitcoinco/web/issues/1391
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/purify.min.js
  app/assets/v2/js/shared.js
  app/retail/templates/shared/footer_scripts.html
Labels: frontend

#1399 External links should open in new tab with noreferrer and noopener
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/ens/base.html
  app/dashboard/templates/ens/ens_pending.html
  app/dashboard/templates/ftux/metamask.html
  app/ethos/templates/redeem_ethos.html
  app/faucet/templates/process_faucet_request.html
  app/retail/templates/about.html
  app/retail/templates/community.html
  app/retail/templates/help.html
  app/retail/templates/index.html
  app/retail/templates/results.html
  app/retail/templates/settings/ens.html
  app/retail/templates/shared/bottom_notification.html
Labels: frontend, in progress

#1401 Open gitcoin profile links on the same tab
  app/retail/templates/about.html
Labels: in progress

#1403 Fix: return of login
  app/assets/v2/css/landing_page.css
  app/retail/templates/index.html
  app/retail/templates/shared/nav.html
Labels: in progress

#1406 landing : updated mobile design
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/landing_page.css
  app/assets/v2/css/newsletter.css
  app/dashboard/templates/shared/nav_auth.html
  app/retail/templates/base.html
  app/retail/templates/index.html
  app/retail/templates/shared/nav.html
  app/retail/templates/slack.html
Labels: frontend

#1411 roundup 6/8
  app/retail/emails.py
Labels: in progress

#1405 Github notification safeguard for local
  app/dashboard/models.py
  docs/THIRD_PARTY_SETUP.md
Labels: backend, bot, in progress, mergeable, notifications

#1412 landing page: final changes
  app/assets/v2/css/base.css
  app/assets/v2/css/bounty.css
  app/assets/v2/css/landing_page.css
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/templates/shared/newsletter.html
  app/retail/templates/index.html
  app/retail/templates/shared/nav.html
  app/retail/views.py
Labels: in progress

#1437 Update django logger and deploy script handling
  app/app/settings.py
  scripts/deploy.bash
  scripts/rollbar.bash
Labels: backend, in progress, needs review

#1190 READY FOR QA : one time approvals for each erc20 token used on gitcoin
  app/app/urls.py
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/tokens_settings.js
  app/assets/v2/js/shared.js
  app/assets/yge/youvegoteth/send.js
  app/dashboard/admin.py
  app/dashboard/migrations/0085_tokenapproval.py
  app/dashboard/models.py
  app/marketing/views.py
  app/retail/templates/settings/settings.html
  app/retail/templates/settings/tokens.html
  package-lock.json
Labels: needs review

#1417 rollbar : quickstart
  app/assets/v2/js/landing_page.js
  app/assets/yge/youvegoteth/pre.js
  app/dashboard/templates/quickstart.html
Labels: frontend, needs review, rollbar

#1343 WIP: add 'stop work & slash' button
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/dashboard/models.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/views.py
Labels: in progress, waiting on contributor, wip

#1448 updated font-size for ftux large devices
  app/assets/v2/css/onboard.css
  app/dashboard/templates/ftux/onboard.html
Labels: frontend, needs review

#1445 ios: updated css + refactored
  app/assets/v2/css/card.css
  app/assets/v2/css/ios.css
  app/dashboard/templates/ios.html
Labels: bug, frontend

#1452 Add name linking to vivek's slack notification and welcomebot
  app/dashboard/notifications.py
  ops/lambdas/welcomebot/app.py
Labels: backend, bot, in progress, notifications, slack

#1439 Simple Nav
  app/assets/v2/css/base.css
  app/assets/v2/css/buttons.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/landing_page.css
  app/assets/v2/js/base.js
  app/dashboard/templates/shared/nav_auth.html
  app/retail/templates/shared/footer.html
  app/retail/templates/shared/nav.html
  app/retail/views.py
Labels: in progress

#1446 Issue Explorer Check in tools for Admin (Vivek)
  app/assets/v2/css/base.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0086_auto_20180613_1328.py
  app/dashboard/models.py
  app/dashboard/templates/bounty_details.html
  app/dashboard/views.py
  app/marketing/mails.py
  app/marketing/management/commands/new_bounties_email.py
  app/marketing/management/commands/pending_start_work_actions.py
  app/marketing/management/commands/remarket_bounties.py
  app/marketing/tests/management/commands/test_remarket_tweet.py
  app/retail/emails.py
  scripts/crontab
Labels: in progress

#1474 Roundup 6/15
  app/retail/emails.py
Labels: in progress

#1495 Fix pytest version
  .travis.yml
  Makefile
  app/faucet/views.py
  docs/RUNNING_LOCALLY_DOCKER.md
  requirements/test.txt
Labels: in progress

#1167 HOLD: releases iOS landing page link - DO NOT MERGE UNTIL IOS APP IS READY
  app/assets/v2/css/gitcoin.css
  app/retail/templates/index.html
  app/retail/templates/landing/ios_banner.html
  app/retail/templates/shared/bottom_notification.html
Labels: dont merge, frontend, in progress

#1444 no flex on alert messages
  app/assets/v2/css/base.css
  app/assets/v2/js/shared.js
Labels: in progress

#1481 Remove unnecessary letter spacing in emails
  app/retail/templates/emails/template.html
Labels: frontend

#1512 Clean up user's personal URL from github
  app/dashboard/templates/profile_details.html
  app/dashboard/templatetags/add_url_schema.py
Labels: backend, bug, in progress, profile

#1524 Fix buttons in standalone avatar page
  app/assets/v2/css/onboard.css
  app/assets/v2/js/pages/onboard.js
Labels: in progress

#1356 Funder form v3
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/select.css
  app/assets/v2/css/submit_bounty.css
  app/assets/v2/images/quotes.png
  app/assets/v2/js/amounts.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/wallet_estimate.js
  app/assets/v2/js/shared.js
  app/assets/v2/js/waiting_room_entertainment.js
  app/assets/yge/youvegoteth/send.js
  app/dashboard/templates/bounty_details.html
  app/dashboard/templates/fulfill_bounty.html
  app/dashboard/templates/increase_bounty.html
  app/dashboard/templates/kill_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/no_metamask_error.html
  app/dashboard/templates/shared/wallet_estimate.html
  app/dashboard/templates/submit_bounty.html
  app/dashboard/utils.py
Labels: in progress, needs review

#1526 Check for slow instead of fast
  app/assets/v2/js/pages/wallet_estimate.js
Labels: in progress

#1530 newsletter 6/22
  app/retail/emails.py
Labels: in progress

#1531 Fix gasPrice on changing recommendation
  app/assets/v2/js/pages/wallet_estimate.js
Labels: in progress

#1479 WIP: Make funder icons circular
  app/assets/v2/css/base.css
  app/assets/v2/css/profile.css
  app/dashboard/templates/profile_details.html
Labels: frontend, waiting on contributor, wip

#1501 1244 how it works
  app/app/urls.py
  app/assets/v2/css/base.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/howitworks.css
  app/assets/v2/css/landing_page.css
  app/assets/v2/images/landing/contributor/how_it_works_accept_work_scr.png
  app/assets/v2/images/landing/contributor/how_it_works_cancel_icon.png
  app/assets/v2/images/landing/contributor/how_it_works_excl_icon.png
  app/assets/v2/images/landing/contributor/how_it_works_fund_scr.png
  app/assets/v2/images/landing/contributor/how_it_works_issues.png
  app/assets/v2/images/landing/contributor/how_it_works_time_icon.png
  app/assets/v2/images/landing/contributor/howitworks1_1.png
  app/assets/v2/images/landing/contributor/howitworks1_2.png
  app/assets/v2/images/landing/contributor/howitworks2_1.png
  app/assets/v2/images/landing/contributor/howitworks2_2.png
  app/assets/v2/images/landing/contributor/howitworks3_1.png
  app/assets/v2/images/landing/contributor/howitworks3_2.png
  app/assets/v2/images/landing/contributor/howitworks4_1.png
  app/assets/v2/images/landing/contributor/howitworks4_2.png
  app/assets/v2/images/landing/contributor/howitworks_accept_submission_icon.png
  app/assets/v2/images/landing/contributor/howitworks_accept_submission_scr.png
  app/assets/v2/images/landing/contributor/howitworks_bottom_1.png
  app/assets/v2/images/landing/contributor/howitworks_bottom_2.png
  app/assets/v2/images/landing/contributor/howitworks_cant_work_icon.png
  app/assets/v2/images/landing/contributor/howitworks_stop_work_scr.png
  app/retail/templates/how_it_works.html
  app/retail/templates/how_it_works_contributor.html
  app/retail/templates/how_it_works_funder.html
  app/retail/templates/shared/nav.html
  app/retail/views.py
Labels: in progress

#1536 Update how it works to use one url
  app/app/urls.py
  app/retail/templates/shared/nav.html
  app/retail/views.py
Labels: backend, in progress

#1533 ftux : further changes
  app/assets/v2/css/avatar_builder.css
  app/assets/v2/css/onboard.css
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/_dashboard/ftux.html
  app/dashboard/templates/ftux/avatar.html
  app/dashboard/templates/ftux/onboard.html
  app/dashboard/templates/ftux/skills.html
Labels: in progress

#1513 Fix selectmenu initialization issue
  app/assets/v2/js/pages/dashboard.js
Labels: frontend, rollbar

#1538 minor changes: added
  app/assets/v2/css/base.css
  app/dashboard/templates/bounty_details.html
  app/retail/templates/shared/nav.html
Labels: in progress

#1540 Fix localstorage issue in firefox
  app/assets/v2/js/avatar_builder.js
Labels: in progress

#1539 all admin actions are in a new line
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty_details.html
Labels: in progress

#1318 Don't save tip information in local storage except current user's
  app/assets/yge/youvegoteth/send.js
Labels: community member, frontend, in progress

#1521 Funder FTUX
  app/app/urls.py
  app/assets/v2/css/quickstart.css
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/ftux/github.html
  app/dashboard/templates/ftux/onboard.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/views.py
  app/retail/templates/index.html
Labels: in progress

#1541 Fix broken CSS from how it works
  app/assets/v2/css/landing_page.css
  app/retail/templates/index.html
  app/retail/templates/landing/pilot.html
Labels: frontend, in progress

#1559 Save Avatar takes you to Profile Page
  app/assets/v2/js/pages/onboard.js
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/views.py
Labels: in progress

#1563 text: Go -> Save
  app/retail/templates/settings/feedback.html
  app/retail/templates/settings/matching.html
  app/retail/templates/settings/slack.html
  app/retail/templates/settings/tokens.html
Labels: in progress

#1564 fix : eslint errors
  app/assets/v2/js/amounts.js
  app/assets/v2/js/shared.js
Labels: in progress

#1555 landing : added growing tree svg
  app/assets/v2/css/landing_page.css
  app/assets/v2/js/landing_page.js
  app/retail/templates/index.html
  app/retail/templates/shared/tree.html
Labels: frontend, mergeable

#1569 Display how it works everywhere except index page
  app/retail/templates/shared/nav.html
Labels: frontend, in progress, ui

#1570 hide message + USD when not available
  app/assets/v2/js/shared.js
  app/dashboard/templates/submit_bounty.html
Labels: in progress

#1571 refs: https://github.com/gitcoinco/web/issues/1568
  app/dashboard/templates/shared/nav_auth.html
Labels: frontend, in progress

#1573 fixed alerts
  app/assets/v2/js/shared.js
Labels: in progress

#1574 nav: fix on mobile
  app/assets/v2/css/gitcoin.css
  app/retail/templates/shared/nav.html
Labels: in progress

#1575 Adds results link to the footer
  app/retail/templates/shared/footer.html
Labels: in progress

#1576 Update where to display how it works again
  app/retail/templates/shared/nav.html
Labels: frontend, in progress

#1551 avatar schwag request form
  app/dashboard/templates/ftux/avatar.html
Labels: in progress

#1583 Newsletter PR
  app/retail/emails.py
Labels: in progress
