Repository gitcoinco/web, pull requests merged in 2019-04, with the labels that each got.

#4080 Adds average star rating calculations
  app/dashboard/models.py
  app/dashboard/views.py
Labels: in progress

#4098 bounty/detail : refactor NDA section
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/addinterest.html
Labels: in progress

#4094 scrub keywords during filter rendering
  app/assets/v2/js/pages/dashboard.js
Labels: in progress

#4078 add cypress framework and visit tests
  Makefile
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/test_visit.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  docs/RUNNING_LOCALLY_DOCKER.md
  package-lock.json
  package.json
Labels: in progress

#4115 Makes changes to the TOS
  app/dashboard/templates/legal/terms.html
Labels: in progress

#4092 Rating modal
  app/app/urls.py
  app/assets/v2/images/emails/rate-capture.png
  app/assets/v2/images/rate-capture.svg
  app/assets/v2/js/capture-rating.js
  app/dashboard/models.py
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/rating_capture.html
  app/dashboard/templates/shared/rate_bounties.html
  app/dashboard/utils.py
  app/dashboard/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/new_bounty_acceptance.html
  app/retail/templates/emails/new_bounty_acceptance.txt
Labels: in progress

#4114 Makes keywords clickable and selectable
  app/assets/v2/css/forms/select.css
  app/assets/v2/css/submit_bounty.css
  app/assets/v2/js/shared.js
  app/dashboard/templates/bounty/new.html
Labels: in progress

#4116 Fixes rating email txt
  app/retail/templates/emails/new_bounty_acceptance.txt
Labels: in progress

#4123 add condition to rating
  app/dashboard/templates/profiles/profile.html
  app/dashboard/templates/shared/rate_bounties.html
Labels: in progress

#4126 fix #4125
  app/assets/v2/js/pages/profile.js
Labels: in progress

#4129 removed duplicate matplotlib
  requirements/base.txt
Labels: in progress

#4127 Fixes the bounty acceptance email in admin
  app/retail/emails.py
Labels: in progress

#4128 Changes top nav gitcoin to bounties and points to bounties page
  app/assets/v2/images/top-bar/bounties_desktop.svg
  app/assets/v2/images/top-bar/bounties_mobile.svg
  app/assets/v2/images/top-bar/codefund-logo.svg
  app/assets/v2/images/top-bar/gitcoin-logo.svg
  app/assets/v2/images/top-bar/gitcoin-symbol.svg
  app/assets/v2/images/top-bar/grants-logo.svg
  app/assets/v2/images/top-bar/grants-symbol.svg
  app/retail/templates/shared/top_nav.html
Labels: in progress

#4130 leaderboard : final touches
  app/assets/v2/css/leaderboard.css
  app/grants/templates/grants/new.html
  app/marketing/views.py
  app/retail/templates/bounties/funder.html
  app/retail/templates/leaderboard.html
Labels: in progress

#4151 fix #4144 nda condition
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/details.html
Labels: in progress

#4143 handle non-metamask web3 browsers
  app/assets/v2/js/metamask-approval.js
  app/assets/v2/js/shared.js
Labels: in progress

#4161 feat: notify funder to extend expiration date before taking action
  app/assets/v2/js/pages/bounty_details.js
Labels: in progress

#4147 change disabled color
  app/assets/v2/css/rating.css
Labels: in progress

#4146 hide featured for private bounties
  app/assets/v2/js/pages/new_bounty.js
Labels: in progress

#4166 fix rating saved data
  app/dashboard/views.py
Labels: 1, in progress

#4168 /funder + /contributor redirects
  app/app/urls.py
  app/assets/v2/css/leaderboard.css
  app/retail/templates/home/index.html
  app/retail/views.py
Labels: 1, in progress

#4177 Change invite bounty email
  app/assets/v2/js/pages/bounty_share.js
  app/dashboard/templates/social_contribution_modal.html
  app/dashboard/views.py
  app/retail/emails.py
  app/retail/templates/emails/share_bounty_email.html
  app/retail/templates/emails/share_bounty_email.txt
Labels: in progress

#4145 Hackathon filter
  app/assets/v2/css/search_bar.css
  app/assets/v2/css/sidebar_search.css
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/dashboard/sidebar_search_hackathon.html
Labels: in progress

#4011 Users list
  app/app/urls.py
  app/assets/v2/js/users.js
  app/dashboard/templates/dashboard/users.html
  app/dashboard/tests/test_users_list.py
  app/dashboard/views.py
Labels: in progress

#4182 remove context in leaderboard
  app/marketing/views.py
Labels: in progress

#4136 check if latest_comment_url is valid when processing gh notifications
  app/gitcoinbot/management/commands/get_notifications.py
Labels: in progress

#4193 041219newsletter
  app/retail/emails.py
Labels: in progress

#4201 hackathon day of updates
  app/app/urls.py
  app/assets/v2/js/base.js
  app/dashboard/templates/dashboard/hackathon/ethhack_2019.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/views.py
  app/retail/templates/shared/top_nav.html
Labels: in progress

#4206 Fix pagination and order by in hackathon
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/templates/dashboard/index.html
Labels: in progress

#4185 Hackathon add sponsor logos
  app/assets/v2/images/hackathon-sponsors/big/Labs-Logo-Black.svg
  app/assets/v2/images/hackathon-sponsors/big/MythX dark.png
  app/assets/v2/images/hackathon-sponsors/big/adex-vector-logo.svg
  app/assets/v2/images/hackathon-sponsors/big/labs-logo-blue.svg
  app/assets/v2/images/hackathon-sponsors/big/labs-logo-white.svg
  app/assets/v2/images/hackathon-sponsors/big/microsoft.svg
  app/assets/v2/images/hackathon-sponsors/big/mythx-light.png
  app/assets/v2/images/hackathon-sponsors/big/pegasys-logo.svg
  app/assets/v2/images/hackathon-sponsors/big/quorum.svg
  app/assets/v2/images/hackathon-sponsors/small/alethio-no-bg.svg
  app/assets/v2/images/hackathon-sponsors/small/alethio-white-bg.svg
  app/assets/v2/images/hackathon-sponsors/small/autom8.svg
  app/assets/v2/images/hackathon-sponsors/small/chainlink-combo-black.svg
  app/assets/v2/images/hackathon-sponsors/small/chainlink-combo-logo.svg
  app/assets/v2/images/hackathon-sponsors/small/chainlink-combo-white.svg
  app/assets/v2/images/hackathon-sponsors/small/chainlink-hexagon.svg
  app/assets/v2/images/hackathon-sponsors/small/coinmark_blue_lg.svg
  app/assets/v2/images/hackathon-sponsors/small/fluence-h.svg
  app/assets/v2/images/hackathon-sponsors/small/fluence.svg
  app/assets/v2/images/hackathon-sponsors/small/kauri_logo_vertical.svg
  app/assets/v2/images/hackathon-sponsors/small/kleros-logo-vertical.svg
  app/assets/v2/images/hackathon-sponsors/small/leapdao.svg
  app/assets/v2/images/hackathon-sponsors/small/logo_poa.svg
  app/assets/v2/images/hackathon-sponsors/small/wordmark_blue copy 6.svg
  app/assets/v2/images/hackathon-sponsors/sponsor-placeholder.svg
  app/dashboard/templates/dashboard/hackathon/ethhack_2019.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/shared/hackathon_sponsors.html
Labels: in progress

#4183 sitemap: update bounties/contibutor
  app/app/sitemaps.py
  app/retail/templates/shared/nav.html
Labels: in progress

#4230 hackathon: prettify
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/dashboard/sidebar_search.html
  app/dashboard/templates/dashboard/sidebar_search_hackathon.html
  app/dashboard/templates/shared/hackathon_sponsors.html
  app/dashboard/views.py
Labels: 3

#4210 fix condition after onboard
  app/assets/v2/js/pages/dashboard.js
Labels: in progress

#4262 refactor code
  app/assets/v2/js/pages/bounty_details.js
Labels: 1

#4137 Suggested Contributor
  app/app/urls.py
  app/assets/v2/css/forms/select.css
  app/assets/v2/css/submit_bounty.css
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/helpers.py
  app/dashboard/templates/shared/issue_details.html
  app/dashboard/views.py
  app/marketing/mails.py
Labels: in progress

#4244 bounty/fee: fixes formula + css cleanup + makes fee editable
  app/assets/v2/css/submit_bounty.css
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/migrations/0030_profile_fee_percentage.py
  app/dashboard/models.py
  app/dashboard/templates/bounty/increase.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/views.py
Labels: 3

#4283 fix: hide network tab on live
  app/dashboard/templates/dashboard/index.html
Labels: 0.5, Gitcoin Hackathon

#4297 grants/index: clean up landing page
  app/assets/v2/css/grants/grant.css
  app/grants/templates/grants/index.html
Labels: 2, Gitcoin Grants

#4302 cleanup grant/fund
  app/grants/templates/grants/fund.html
Labels: 1
