Repository gitcoinco/web, pull requests merged in 2019-07, with the labels that each got.

#4717 chore: remove dead code
  app/dashboard/templates/bounty/new.html
Labels: 1, Gitcoin Bounties, tech-debt

#4719 bug: trigger alert notifying grant ownership process
  app/assets/v2/js/grants/detail.js
  app/grants/admin.py
  app/grants/templates/grants/detail/index.html
Labels: 2, Gitcoin Grants, bug, frontend

#4720 chore: grant/details cleanup
  app/assets/v2/css/buttons.css
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/detail.js
  app/grants/templates/grants/detail/index.html
  app/grants/templates/grants/detail/info.html
Labels: 1, Gitcoin Grants, frontend

#4602 Add default ordering users in user directory
  app/dashboard/views.py
Labels: sprint 13

#4613 Add filtering by applicants in bounties explorer
  app/assets/v2/js/pages/dashboard.js
  app/dashboard/router.py
  app/dashboard/templates/dashboard/sidebar_search.html
Labels: Gitcoin Bounties, sprint 13, waiting on contributor

#4605 Issue 3907 profile header update
  app/app/urls.py
  app/assets/v2/css/profile.css
  app/assets/v2/js/pages/profile-edit.js
  app/assets/v2/js/pages/profile.js
  app/assets/wallpapers/11 fps.gif
  app/assets/wallpapers/14 fps.gif
  app/assets/wallpapers/16by9.gif
  app/assets/wallpapers/7 fps.gif
  app/assets/wallpapers/burst-blue.png
  app/assets/wallpapers/burst-blue.svg
  app/assets/wallpapers/burst-pink.png
  app/assets/wallpapers/burst-pink.svg
  app/assets/wallpapers/burst-yellow.png
  app/assets/wallpapers/burst-yellow.svg
  app/assets/wallpapers/cannon-blue-yellow.png
  app/assets/wallpapers/cannon-blue-yellow.svg
  app/assets/wallpapers/cannon-green-blue.png
  app/assets/wallpapers/cannon-green-blue.svg
  app/assets/wallpapers/cannon-yellow-pink.png
  app/assets/wallpapers/cannon-yellow-pink.svg
  app/assets/wallpapers/dvdptr-blue-green.png
  app/assets/wallpapers/dvdptr-blue-green.svg
  app/assets/wallpapers/dvdptr-blue-yellow.png
  app/assets/wallpapers/dvdptr-blue-yellow.svg
  app/assets/wallpapers/gitbot-banner.png
  app/assets/wallpapers/gitbot-banner.svg
  app/assets/wallpapers/network-blue.png
  app/assets/wallpapers/network-blue.svg
  app/assets/wallpapers/network-pink.png
  app/assets/wallpapers/network-pink.svg
  app/assets/wallpapers/network-yellow.png
  app/assets/wallpapers/network-yellow.svg
  app/assets/wallpapers/polkadot-banner.png
  app/assets/wallpapers/polkadot-banner.svg
  app/assets/wallpapers/polkadot-banner1.png
  app/assets/wallpapers/polkadot-banner1.svg
  app/assets/wallpapers/raw/burst-cannon-network.figma.fig
  app/assets/wallpapers/rocket-banner.png
  app/assets/wallpapers/rocket-banner.svg
  app/dashboard/helpers.py
  app/dashboard/migrations/0040_profile_profile_wallpaper.py
  app/dashboard/models.py
  app/dashboard/templates/profiles/profile.html
  app/dashboard/views.py
Labels: sprint 13

#4741 fix: base_name -> basename
  app/avatar/router.py
Labels: tech-debt

#4854 bug: fix grant owner address etherscan link
  app/assets/v2/js/abi.js
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/index.js
  app/assets/v2/js/grants/new.js
  app/assets/v2/js/pages/bounty_details.js
  app/grants/templates/grants/detail/index.html
Labels: Gitcoin Grants

#4818 massively simplifies the activity tabs on profile
  app/dashboard/models.py
  app/dashboard/views.py
Labels: Gitcoin Profile

#4830 chore: css fixes on featured bounties
  app/assets/v2/css/featured-bounties.css
  app/dashboard/templates/dashboard/index.html
Labels: 0.5, Gitcoin Bounties, ui

#4837 chore: update node dependencies
  js-sdk/package-lock.json
  js-sdk/package.json
  js-sdk/yarn.lock
  package-lock.json
  package.json
  yarn.lock
Labels: 0.5
