Repository gitcoinco/web, pull requests merged in 2019-03, with the labels that each got.

#3858 integrate codefund into bounty landing pages
  app/assets/v2/css/gitcoin.css
  app/retail/templates/bounties/contributor.html
  app/retail/templates/bounties/funder.html
Labels: 2

#3709 feedback implementation (continuation of #3424)
  app/app/urls.py
  app/assets/v2/css/base.css
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/dashboard/admin.py
  app/dashboard/helpers.py
  app/dashboard/migrations/0015_auto_20190228_1027.py
  app/dashboard/migrations/0018_merge_20190307_1314.py
  app/dashboard/models.py
  app/dashboard/templates/bounty/fulfill.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/rating.html
  app/dashboard/utils.py
  app/dashboard/views.py
Labels: 5

#3962 homepage fixes
  app/assets/v2/css/home.css
  app/retail/templates/home/index.html
  app/retail/views.py
Labels: 1, Gitcoin Marketing

#3994 fix unclosed div
  app/dashboard/templates/profiles/profile.html
Labels: in progress

#3998 Fix/grants members
  app/assets/v2/css/grants/detail.css
Labels: in progress

#3995 Hacklanding fixes
  app/assets/v2/css/buttons.css
  app/assets/v2/css/colors.css
  app/assets/v2/css/ethhack2019.css
  app/assets/v2/images/hackathon/bg.jpg
  app/assets/v2/images/hackathon/bg2.jpg
  app/assets/v2/images/hackathon/bot.svg
  app/assets/v2/images/hackathon/ethback2.png
  app/assets/v2/images/hackathon/ethmain.svg
  app/assets/v2/images/hackathon/ethtext.png
  app/assets/v2/images/hackathon/microsoft.svg
  app/assets/v2/images/hackathon/plus.svg
  app/dashboard/templates/dashboard/hackathon/ethhack_2019.html
  app/dashboard/templates/social_contribution_modal.html
  app/dashboard/views.py
Labels: in progress

#4024 skip grants migration 0011
  app/grants/migrations/0011_auto_20190221_2050.py
Labels: in progress

#4017 Infura changes
  app/app/local.env
  app/app/settings.py
  app/dashboard/tests/test_dashboard_utils.py
  app/dashboard/utils.py
  docs/ENVIRONMENT_VARIABLES.md
Labels: in progress

#4033 fix production logging watchtower setup
  app/app/settings.py
Labels: in progress

#4026 fix node security vulnerabilities
  app/assets/v2/js/metamask-approval.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/faucet_form.js
  app/assets/v2/js/shared.js
  package-lock.json
  package.json
Labels: in progress, tech-debt

#4034 temporarily disable watchtower logging
  app/app/settings.py
Labels: in progress

#4043 Require login for invite code URL
  app/dashboard/views.py
Labels: in progress

#4046 added carousel to funder/contributor landing page
  app/assets/v2/css/fontawesome-all.min.css
  app/assets/v2/css/landing_page.css
  app/assets/v2/images/presskit/illustrations/regulus-white.svg
  app/retail/templates/bounties/contributor.html
  app/retail/templates/bounties/funder.html
  app/retail/templates/shared/onboard_slider.html
  app/retail/views.py
Labels: in progress

#3961 bounties: fee integration
  app/app/urls.py
  app/assets/onepager/js/send.js
  app/assets/v2/css/base.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/submit_bounty.css
  app/assets/v2/js/avatar_builder.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/bulk_payout.js
  app/assets/v2/js/pages/change_bounty.js
  app/assets/v2/js/pages/fulfill_bounty.js
  app/assets/v2/js/pages/increase_bounty.js
  app/assets/v2/js/pages/kill_bounty.js
  app/assets/v2/js/pages/kudos_send.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/pages/process_bounty.js
  app/assets/v2/js/pages/process_refund_request.js
  app/assets/v2/js/pages/refund_request.js
  app/assets/v2/js/pages/tokens_settings.js
  app/assets/v2/js/pages/wallet_estimate.js
  app/assets/v2/js/shared.js
  app/assets/v2/js/tokens.js
  app/dashboard/admin.py
  app/dashboard/helpers.py
  app/dashboard/migrations/0019_refundfeerequest.py
  app/dashboard/migrations/0020_auto_20190312_1926.py
  app/dashboard/migrations/0021_auto_20190315_1421.py
  app/dashboard/migrations/0022_merge_20190319_1251.py
  app/dashboard/migrations/0025_merge_20190327_1106.py
  app/dashboard/models.py
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bounty/increase.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/bounty/process_refund_request.html
  app/dashboard/templates/bounty/refund_request.html
  app/dashboard/templates/shared/no_issue_error.html
  app/dashboard/templates/shared/wallet_estimate.html
  app/dashboard/views.py
  app/faucet/templates/faucet_form.html
Labels: Gitcoin Bounties

#4051 Add image to share and fixes
  app/assets/v2/images/ethhack_2019_media.png
  app/dashboard/templates/dashboard/hackathon/ethhack_2019.html
  app/dashboard/views.py
  app/retail/templates/shared/cards_pic.html
Labels: in progress

#4050 Fix matching logic
  app/assets/v2/js/pages/dashboard.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/router.py
  app/marketing/management/commands/new_bounties_email.py
Labels: in progress

#4058 Fix required field in admin
  app/dashboard/migrations/0026_auto_20190328_1314.py
  app/dashboard/models.py
Labels: in progress

#4055 Fix condition for nda link
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/details.html
Labels: in progress

#4063 remove cloudwatch
  app/app/settings.py
Labels: in progress

#4065 Retrieve bounty document for new bounty creation on transaction update
  app/dashboard/helpers.py
Labels: in progress
