Repository gitcoinco/web, pull requests merged in 2019-02, with the labels that each got.

#3680 Fix spacing issue in bounty info
  app/dashboard/templates/bounty/details.html
Labels: Gitcoin Bounties, frontend

#3687 Subscription Token Address Fix
  app/assets/v2/js/grants/fund.js
  app/grants/templates/grants/fund.html
Labels: Gitcoin Grants

#3731 fix: updated django 2.1.5 -> 2.1.6
  requirements/base.txt
Labels: tech-debt

#3710 Ks grant image fix
  app/assets/v2/js/grants/new.js
  app/grants/views.py
Labels: Gitcoin Grants

#3743 onboard + grant/new fixes
  app/dashboard/views.py
  app/grants/templates/grants/detail/index.html
  app/grants/templates/grants/new.html
  app/retail/templates/bounties/funder.html
Labels: bug

#3742 tech-debt: purge extra code
  app/assets/v2/css/animate.min.css
  app/assets/v2/css/base.css
  app/assets/v2/css/mission.css
  app/assets/v2/css/vision.css
  app/assets/v2/js/animate.min.js
  app/assets/v2/js/note.js
  app/dashboard/templates/bounty/increase.html
  app/dashboard/templates/bulk_payout_bounty.html
  app/dashboard/templates/contribute_bounty.html
  app/dashboard/templates/payout_bounty.html
  app/dashboard/templates/process_bounty.html
  app/dashboard/templates/shared/bounty_nav.html
  app/dashboard/templates/shared/connect_metamask.html
  app/dashboard/templates/shared/network_status.html
  app/dashboard/templates/shared/no_metamask_error.html
  app/dashboard/templates/shared/onepager_auth.html
  app/dashboard/templates/shared/send_tip_nav.html
  app/dashboard/templates/shared/unlock_metamask.html
  app/dashboard/templates/social_contribution.html
  app/dashboard/templates/social_contribution_modal.html
  app/faucet/templates/shared/faucet_unlock_metamask.html
  app/kudos/templates/transaction/receive_bulk.html
  app/retail/templates/about.html
  app/retail/templates/bounties/funder/hero.html
  app/retail/templates/emails/bounty_roundup.html
  app/retail/templates/help.html
  app/retail/templates/mission.html
  app/retail/templates/not_a_token.html
  app/retail/templates/results.html
  app/retail/templates/settings/settings.html
  app/retail/templates/shared/footer_scripts.html
  app/retail/templates/shared/head.html
  app/retail/templates/shared/what_is_gitcoin.html
  app/retail/templates/vision.html
  app/retail/templates/whitepaper_accesscode.html
  app/retail/templates/whitepaper_new.html
  app/retail/views.py
Labels: tech-debt

#3773 purge styleguide-alpha
  app/app/urls.py
  app/retail/templates/ui_inventory.html
  app/retail/views.py
  docs/CONTRIBUTING.md
Labels: tech-debt

#2013 pages/bounty_details: Fix for bad activity stream entries.
  app/assets/v2/js/pages/bounty_details.js
Labels: needs review

#3785 [WIP] remove jquery ui in explorer
  app/assets/v2/css/base.css
  app/assets/v2/js/base.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/dashboard/index.html
  app/dashboard/templates/dashboard/sidebar_search.html
  app/dashboard/templates/shared/bounty-popover.html
  app/dashboard/templates/shared/permissions_type_tooltip.html
  app/dashboard/templates/shared/project_type_tooltip.html
  app/dashboard/templates/shared/status_tooltip.html
  app/retail/templates/shared/result.html
Labels: tech-debt

#3814 homepage + pricing fixes
  app/assets/v2/css/base.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/retail/plans.css
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/shared.js
  app/dashboard/templates/shared/no_metamask_error.html
  app/retail/templates/home/index.html
  app/retail/templates/pricing/subscribe.html
  docs/STYLEGUIDE.md
Labels: 2, frontend, tech-debt

#3821 detail: clean up info-section
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/details.html
Labels: 1, tech-debt

#3834 Fixes #3833 Improve Installation docs
  app/app/local.env
  docs/RUNNING_LOCALLY.md
  docs/RUNNING_LOCALLY_DOCKER.md
Labels: documentation

#3831 Add girl-ey avatar clothing options
  app/assets/v2/images/avatar/Clothing/blouse-4242F4.svg
  app/assets/v2/images/avatar/Clothing/blouse-43B9F9.svg
  app/assets/v2/images/avatar/Clothing/blouse-684A23.svg
  app/assets/v2/images/avatar/Clothing/blouse-CCCCCC.svg
  app/assets/v2/images/avatar/Clothing/blouse-F48914.svg
  app/assets/v2/images/avatar/Clothing/blouse-FFCC3B.svg
  app/assets/v2/images/avatar/Clothing/coat-4242F4.svg
  app/assets/v2/images/avatar/Clothing/coat-43B9F9.svg
  app/assets/v2/images/avatar/Clothing/coat-684A23.svg
  app/assets/v2/images/avatar/Clothing/coat-CCCCCC.svg
  app/assets/v2/images/avatar/Clothing/coat-F48914.svg
  app/assets/v2/images/avatar/Clothing/coat-FFCC3B.svg
  app/assets/v2/images/avatar/Clothing/crochettop-4242F4.svg
  app/assets/v2/images/avatar/Clothing/crochettop-43B9F9.svg
  app/assets/v2/images/avatar/Clothing/crochettop-684A23.svg
  app/assets/v2/images/avatar/Clothing/crochettop-CCCCCC.svg
  app/assets/v2/images/avatar/Clothing/crochettop-F48914.svg
  app/assets/v2/images/avatar/Clothing/crochettop-FFCC3B.svg
  app/assets/v2/images/avatar/Clothing/polkadotblouse-4242F4.svg
  app/assets/v2/images/avatar/Clothing/polkadotblouse-43B9F9.svg
  app/assets/v2/images/avatar/Clothing/polkadotblouse-684A23.svg
  app/assets/v2/images/avatar/Clothing/polkadotblouse-CCCCCC.svg
  app/assets/v2/images/avatar/Clothing/polkadotblouse-F48914.svg
  app/assets/v2/images/avatar/Clothing/polkadotblouse-FFCC3B.svg
  app/avatar/templates/clothing/blouse.txt
  app/avatar/templates/clothing/coat.txt
  app/avatar/templates/clothing/crochettop.txt
  app/avatar/templates/clothing/polkadotblouse.txt
  app/avatar/utils.py
  app/dashboard/tests/__init__.py
Labels: Gitcoin Avatar
