Repository gitcoinco/web, pull requests merged in 2019-01, with the labels that each got.

#3359 grantz cleanup
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/detail.js
  app/assets/v2/js/grants/shared.js
  app/grants/templates/grants/cancel.html
  app/grants/templates/grants/detail.html
  app/grants/views.py
Labels: Gitcoin Grants

#3270 purge: bounties universe
  .gitignore
  app/app/settings.py
  app/app/urls.py
  app/assets/v2/css/external_bounties/bounties.css
  app/assets/v2/css/external_bounties/bounty.css
  app/assets/v2/js/pages/offchain_bounties.js
  app/external_bounties/__init__.py
  app/external_bounties/admin.py
  app/external_bounties/apps.py
  app/external_bounties/forms.py
  app/external_bounties/management/__init__.py
  app/external_bounties/management/commands/__init__.py
  app/external_bounties/management/commands/sync_bounty0x.py
  app/external_bounties/management/commands/sync_gitcoin.py
  app/external_bounties/management/commands/sync_known_github_repos.py
  app/external_bounties/migrations/0001_initial.py
  app/external_bounties/migrations/__init__.py
  app/external_bounties/models.py
  app/external_bounties/router.py
  app/external_bounties/templates/external_bounties.html
  app/external_bounties/templates/external_bounties_new.html
  app/external_bounties/templates/external_bounties_show.html
  app/external_bounties/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/admin/index.html
  app/retail/templates/emails/bounty_roundup.html
  app/retail/templates/shared/head.html
  docs/API.md
  pydocmd.yml
  scripts/crontab
Labels: tech-debt

#3379 tech-debt
  app/app/templates/shared/current_profile.html
  app/app/urls.py
  app/assets/v2/css/about.css
  app/assets/v2/css/base.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/ios.css
  app/assets/v2/css/landing_page.css
  app/assets/v2/images/icons/gitcoin.svg
  app/assets/v2/images/icons/keyboard.png
  app/assets/v2/images/icons/link.png
  app/assets/v2/images/icons/magic_mouse.png
  app/assets/v2/images/ios/appstore-gradient.png
  app/assets/v2/images/ios/appstore.png
  app/assets/v2/images/ios/gitcoin_hover.gif
  app/assets/v2/images/ios/iphone.png
  app/assets/v2/images/ios/iphone_crop.png
  app/assets/v2/images/ios/play.png
  app/assets/v2/js/base.js
  app/dashboard/ios.py
  app/dashboard/templates/shared/bounty_def.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/templates/toolbox.html
  app/kudos/templates/shared/kudos_nav.html
  app/retail/templates/getgitcoin.html
  app/retail/templates/index.html
  app/retail/templates/mission.html
  app/retail/templates/products.html
  app/retail/templates/shared/footer.html
  app/retail/templates/shared/head.html
  app/retail/templates/shared/mailchimp.html
  app/retail/views.py
  pydocmd.yml
Labels: frontend, tech-debt

#3416 faucet: fixed alert banner
  app/dashboard/templates/shared/no_metamask_error.html
  app/faucet/templates/faucet_form.html
  app/faucet/templates/shared/faucet_network_status.html
  app/faucet/templates/shared/faucet_no_metamask_error.html
  app/faucet/templates/shared/faucet_over_balance_error.html
  app/faucet/templates/shared/faucet_unlock_metamask.html
Labels: frontend, tech-debt

#2950 [WOC] Reserve bounties
  app/assets/v2/css/bounty.css
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/pages/change_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/assets/v2/js/user-search.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0005_auto_20190103_2227.py
  app/dashboard/models.py
  app/dashboard/router.py
  app/dashboard/templates/bounty/change.html
  app/dashboard/templates/bounty/details.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/shared/issue_details.html
  app/dashboard/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/reserved_issue.html
  app/retail/templates/emails/reserved_issue.txt
Labels: Gitcoin Bounties, backend, frontend, needs review, needs-testing, new feature

#2956 Add a field to store estimated hours for bounties
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/helpers.py
  app/dashboard/migrations/0006_bounty_estimated_hours.py
  app/dashboard/models.py
  app/dashboard/tests/test_dashboard_models.py
Labels: Gitcoin Bounties, backend, data, enhancement

#2683 [WOC] Define function used during race condition before triggering condition
  app/assets/v2/js/pages/dashboard.js
Labels: bug, frontend, waiting on contributor

#3441 warns users not to leave pending page on grants
  app/assets/v2/js/grants/cancel_subscription.js
  app/assets/v2/js/grants/fund.js
  app/assets/v2/js/grants/new.js
  app/assets/v2/js/grants/shared.js
Labels: Gitcoin Grants

#3464 Fixes Grants decimal issues
  app/grants/templates/grants/profile/body.html
  app/retail/templates/emails/grants/new_supporter.html
  app/retail/templates/emails/grants/new_supporter.txt
  app/retail/templates/emails/grants/subscription_terminated.html
  app/retail/templates/emails/grants/successful_contribution.html
  app/retail/templates/emails/grants/support_cancellation.html
  app/retail/templates/emails/grants/support_cancellation.txt
  app/retail/templates/emails/grants/thank_you_for_supporting.html
  app/retail/templates/emails/grants/thank_you_for_supporting.txt
  app/retail/templates/emails/grants/transaction_summary.html
  app/retail/templates/emails/grants/transaction_summary.txt
Labels: Gitcoin Grants

#3221 code: Notifications
  app/app/settings.py
  app/app/templates/shared/rain.html
  app/app/urls.py
  app/assets/onepager/css/main.css
  app/assets/v2/css/box_redeem.css
  app/assets/v2/css/buttons.css
  app/assets/v2/css/external_bounties/checkboxes.css
  app/assets/v2/css/gitcoin.css
  app/assets/v2/css/mission.css
  app/assets/v2/css/notifications.css
  app/assets/v2/css/rain.css
  app/assets/v2/images/favicon.ico/manifest.json
  app/assets/v2/images/favicon_local.ico/manifest.json
  app/assets/v2/images/header-bg.png
  app/assets/v2/js/base.js
  app/assets/v2/js/moment.min.js
  app/assets/v2/js/note.js
  app/assets/v2/js/notifications.js
  app/dashboard/templates/onepager/base.html
  app/dashboard/templates/onepager/receive.html
  app/dashboard/templates/onepager/send2.html
  app/dashboard/templates/shared/labs_nav.html
  app/dashboard/templates/shared/nav_auth.html
  app/dashboard/templates/shared/notifications.html
  app/dashboard/templates/shared/onepager_auth.html
  app/grants/templates/grants/nav.html
  app/grants/templates/grants/stub/nav.html
  app/inbox/__init__.py
  app/inbox/admin.py
  app/inbox/apps.py
  app/inbox/migrations/0001_initial.py
  app/inbox/migrations/__init__.py
  app/inbox/models.py
  app/inbox/signals.py
  app/inbox/templates/inbox.html
  app/inbox/urls.py
  app/inbox/utils.py
  app/inbox/views.py
  app/kudos/templates/shared/kudos_nav.html
  app/kudos/templates/transaction/kudos_auth.html
  app/retail/templates/mission.html
  app/retail/templates/not_a_token.html
  app/retail/templates/results.html
  app/retail/templates/shared/footer_scripts.html
  app/retail/templates/shared/head.html
  app/retail/templates/shared/minihero.html
  app/retail/templates/shared/nav.html
  app/retail/templates/vision.html
Labels: in progress, needs review

#3540 grant/detail: modal + tooltip
  app/assets/v2/css/base.css
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/detail.js
  app/grants/templates/grants/detail/index.html
  app/grants/templates/grants/index.html
  app/kudos/templates/kudos_details.html
  app/retail/templates/shared/head.html
Labels: tech-debt

#3552 bounty/new + bounty/fulfill revamp
  app/assets/v2/css/base.css
  app/assets/v2/css/forms/button.css
  app/assets/v2/css/submit_bounty.css
  app/dashboard/templates/bounty/fulfill.html
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/shared/github_username.html
  app/dashboard/templates/shared/issue_details.html
  app/dashboard/templates/shared/notification_email.html
  app/dashboard/templates/shared/pricing.html
  app/retail/templates/shared/head.html
Labels: tech-debt

#3598 bounty/new : update funding org label
  app/dashboard/templates/bounty/new.html
  app/dashboard/templates/profiles/profile.html
Labels: Gitcoin Bounties, frontend

#3574 grant/new: multiselect
  app/assets/v2/css/grants/grant.css
  app/grants/templates/grants/new.html
  docs/STYLEGUIDE.md
Labels: tech-debt

#3615 base cleanup
  app/app/sitemaps.py
  app/app/urls.py
  app/dashboard/views.py
  app/kudos/templates/kudos_about.html
  app/kudos/templates/transaction/base.html
  app/retail/templates/bounties/contributor.html
  app/retail/templates/bounties/contributor/activity.html
  app/retail/templates/bounties/contributor/benefits.html
  app/retail/templates/bounties/contributor/explorer.html
  app/retail/templates/bounties/contributor/gitcoiners.html
  app/retail/templates/bounties/contributor/hero.html
  app/retail/templates/bounties/contributor/projects.html
  app/retail/templates/bounties/funder.html
  app/retail/templates/bounties/funder/benefits.html
  app/retail/templates/bounties/funder/hero.html
  app/retail/templates/bounties/funder/howworks.html
  app/retail/templates/bounties/funder/pilot.html
  app/retail/templates/bounties/funder/press.html
  app/retail/templates/emails/template.html
  app/retail/templates/index.html
  app/retail/templates/ui_inventory.html
  app/retail/views.py
Labels: Gitcoin.co, tech-debt
