Repository gitcoinco/web, pull requests merged in 2019-08, with the labels that each got.

#4878 purge: remove grant ownership feature
  app/app/urls.py
  app/assets/v2/css/grants/detail.css
  app/assets/v2/js/grants/detail.js
  app/grants/admin.py
  app/grants/migrations/0027_remove_grant_request_ownership_change.py
  app/grants/models.py
  app/grants/templates/grants/detail/index.html
  app/grants/templates/grants/detail/info.html
  app/grants/views.py
  app/marketing/mails.py
  app/retail/emails.py
  app/retail/templates/emails/grants/change_owner_accept.html
  app/retail/templates/emails/grants/change_owner_accept.txt
  app/retail/templates/emails/grants/change_owner_notify.html
  app/retail/templates/emails/grants/change_owner_notify.txt
  app/retail/templates/emails/grants/change_owner_reject.html
  app/retail/templates/emails/grants/change_owner_reject.txt
  app/retail/templates/emails/grants/change_owner_request.html
  app/retail/templates/emails/grants/change_owner_request.txt
Labels: Gitcoin Grants

#4948 replace showdown with highlight + markdown
  .eslintignore
  .stylelintignore
  app/assets/v2/css/bounty.css
  app/assets/v2/css/highlight_github.css
  app/assets/v2/js/lib/highlight.js
  app/assets/v2/js/lib/markdown-it.js
  app/assets/v2/js/lib/showdown.js
  app/assets/v2/js/pages/bounty_details.js
  app/dashboard/templates/bounty/details.html
Labels: Gitcoin Bounties

#4986 Ambassador Check-In API extension for alpha
  app/dashboard/models.py
  app/dashboard/router.py
Labels: api, needs review

#5067 chore: tech upgrade
  js-sdk/package-lock.json
  js-sdk/package.json
  js-sdk/yarn.lock
  package-lock.json
  package.json
  requirements/base.txt
Labels: 2, Sprint 17, tech-debt
