Repository gitcoinco/web, pull requests merged in 2019-06, with the labels that each got.

#4583 sentry: fix undefined error
  app/assets/v2/js/base.js
  app/assets/v2/js/grants/shared.js
  app/assets/v2/js/pages/bounty_details.js
  app/assets/v2/js/shared.js
  app/grants/templates/grants/shared/shared_scripts.html
Labels: 1

#4642 feat: added in beyond hackathon
  app/app/urls.py
  app/assets/v2/css/fontawesome-all.min.css
  app/assets/v2/css/hackathons/static.css
  app/assets/v2/images/hackathon/beyond_block/logo.png
  app/dashboard/context/hackathon.py
  app/dashboard/templates/dashboard/hackathon/index.html
  app/dashboard/views.py
Labels: 2

#2811 [WOC] PR@2764: Update corner case canceling started issue
  app/assets/v2/js/pages/kill_bounty.js
Labels: frontend
