Repository gitcoinco/web, pull requests merged in 2020-09, with the labels that each got.

#7490 updates outdated etherscan txn find/replace functionality to use blocknative
  app/app/settings.py
  app/app/urls.py
  app/dashboard/models.py
  app/dashboard/sync/eth.py
  app/economy/admin.py
  app/economy/migrations/0004_txupdate.py
  app/economy/models.py
  app/economy/tx.py
  app/economy/utils.py
  app/kudos/management/commands/update_tx_status.py
  app/perftools/views.py
Labels: API KEY NEEDED, hotfix-stable

#7510 Start tx validator v2, and fix bug in zkSync validations
  app/economy/tx.py
  app/grants/models.py
Labels: hotfix-stable

#7146 New Email for Tribe Members about Hackathon Prizes
  app/app/urls.py
  app/assets/v2/images/emails/email_header_hackathon.png
  app/marketing/mails.py
  app/marketing/management/commands/tribe_hackathon_prizes_email.py
  app/marketing/utils.py
  app/retail/emails.py
  app/retail/templates/emails/bounty.html
  app/retail/templates/emails/shared_bounty_actions.html
  app/retail/templates/emails/template.html
  app/retail/templates/emails/tribe_hackathon_prizes.html
  app/retail/templates/emails/tribe_hackathon_prizes.txt
  scripts/crontab
Labels: October Hacks

#7316 Add events section to hackathons
  app/app/settings.py
  app/app/urls.py
  app/assets/v2/images/hackathon/check.svg
  app/assets/v2/images/hackathon/demo.png
  app/assets/v2/images/hackathon/demo.svg
  app/assets/v2/images/hackathon/formation.svg
  app/assets/v2/images/hackathon/office.svg
  app/assets/v2/images/hackathon/pitch.svg
  app/assets/v2/images/hackathon/workshop.svg
  app/assets/v2/js/pages/dashboard-hackathon.js
  app/assets/v2/js/vue-components.js
  app/dashboard/migrations/0151_hackathonevent_calendar_id.py
  app/dashboard/models.py
  app/dashboard/templates/dashboard/index-vue.html
  app/dashboard/views.py
Labels: API KEY NEEDED
