Repository gitcoinco/web, pull requests merged in 2021-06, with the labels that each got.

#8976 Alters QL banner to post 48hr version
  app/assets/v2/js/ql-banner.js
  app/assets/v2/scss/ql-banner.scss
  app/retail/templates/shared/top_nav.html
Labels: hotfix-stable

#8984 fix: Ensures notification box and search box remain scrollable for short viewports
  app/assets/v2/scss/notifications.scss
  app/assets/v2/scss/search.scss
Labels: bug, grants_round_10

#8983 fix: Prevents navbar.js from loading on bulk-add (to cart)
  app/dashboard/templates/shared/nav_auth.html
  app/grants/templates/grants/bulk_add_to_cart.html
Labels: bug, grants_round_10

#8985 feature: Implements the "Me Menu"
  app/assets/v2/js/navbar.js
  app/assets/v2/scss/navbar.scss
  app/dashboard/templates/shared/menu.html
  app/dashboard/templates/shared/nav_auth.html
Labels: grants_round_10

#9019 bug: fix avatar bug reported on sentry
  app/avatar/models.py
Labels: bug

#9022 bug: remove reference to gitcoin chat on hack project
  app/assets/v2/js/vue-components.js
Labels: bug, hotfix-stable

#9024 sentry: bug fixes (20k)
  app/assets/v2/js/pages/kudos_bulk_receive.js
  app/retail/views.py
Labels: bug, hotfix-stable

#9012 Gpg/countdown grants
  app/assets/v2/js/vue-components.js
  app/grants/templates/grants/landingpage.html
  app/grants/templates/grants/shared/landing_qf_active.html
  app/grants/views.py
Labels: hotfix-stable

#9044 fix broken emails
  app/retail/templates/emails/bounty_startwork_expire_warning.html
  app/retail/templates/emails/new_bounty.html
Labels: gpg - bug

#9089 Restores variables lost in SHA: c10f867f994160feb7d2af8c3b3a21da0994ddb8
  app/grants/views.py
Labels: hotfix-stable

#9092 sentry fixes
  app/dashboard/views.py
  app/kudos/views.py
  app/retail/templates/home/index2021.html
Labels: bug

#9106 fix: Use created_on date rather than modified_on to source recent contributions
  app/retail/emails.py
Labels: hotfix-stable

#9117 hotfix: new grant email CTAs
  app/retail/templates/emails/grants/new_grant.html
Labels: bug, grants_round_10

#9118 fix https://sentry.io/organizations/gitcoin/issues/2457438215/
  app/dashboard/views.py
Labels: hotfix-stable

#9135 Converts build_collection_thumbnails to a celery task
  app/grants/management/commands/build_collection_thumbnails.py
  app/grants/tasks.py
Labels: hotfix-stable

#9142 fix: Corrects verbiage used on the Twitter verification modal
  app/assets/v2/js/pages/profile-trust.js
Labels: hotfix-stable

#9140 fix: Ensures elements are present before activating the nav
  app/assets/v2/js/navbar.js
Labels: hotfix-stable

#9144 bug: fix sentry reports (50k reports + 35k users affected)
  app/assets/v2/js/navbar.js
Labels: bug, hotfix-stable

#9149 fix unshadowban function on admin
  app/dashboard/admin.py
Labels: hotfix-stable

#9151 Fix townsquare filters
  app/townsquare/templates/townsquare/shared/tag.html
Labels: hotfix-stable

#9153 Fix cart link
  app/assets/v2/js/theme_switcher.js
Labels: hotfix-stable

#9157 Fix cart match
  app/assets/v2/js/cart.js
Labels: hotfix-stable

#9155 Highlights the grants owner to staff users
  app/grants/templates/grants/detail/template-grant-details.html
Labels: hotfix-stable

#9143 fix decimals fees on bounties
  app/assets/v2/js/pages/new_bounty.js
Labels: hotfix-stable

#9025 tezos crosschain | bounties/hackathons
  app/assets/v2/images/chains/tezos.svg
  app/assets/v2/js/pages/bounty_details2.js
  app/assets/v2/js/pages/hackathon_new_bounty.js
  app/assets/v2/js/pages/new_bounty.js
  app/dashboard/management/commands/sync_pending_fulfillments.py
  app/dashboard/models.py
  app/dashboard/sync/tezos.py
  app/dashboard/templates/bounty/new_bounty.html
  app/dashboard/templates/dashboard/hackathon/new_bounty.html
  app/dashboard/utils.py
  app/dashboard/views.py
Labels: gpg - crosschain/tezos

#9165 chore: ensure get_prices doesn't break with missing data
  app/economy/management/commands/get_prices.py
Labels: bug

#9169 fix: Ensures the submenu els are present before attempting to display them
  app/assets/v2/js/navbar.js
Labels: hotfix-stable

#9177 GITC-56: Allows service/metadata to be accessible when its not at the start of the url
  app/app/urls.py
Labels: hotfix-stable

#9191 GITC-69: Fix activity donations to gitcoin
  app/assets/v2/js/cart.js
Labels: hotfix-stable

#9176 GITC-49: Adds notion integration to support sybil-hunting
  app/app/local.env
  app/app/settings.py
  app/app/utils.py
  app/grants/tasks.py
  app/grants/utils.py
  app/grants/views.py
  app/marketing/mails.py
Labels: hotfix-stable

#9168 feat: algorand grants integration
  app/assets/v2/js/cart.js
  app/assets/v2/js/grants/_detail-component.js
  app/assets/v2/js/grants/_new.js
  app/assets/v2/js/grants/cart/algorand_extension.js
  app/assets/v2/js/grants/funding.js
  app/assets/v2/js/pages/bounty_detail/algorand_extension.js
  app/assets/v2/js/pages/bounty_details2.js
  app/grants/admin.py
  app/grants/management/commands/sync_pending_contributions.py
  app/grants/migrations/0120_auto_20210622_1021.py
  app/grants/models.py
  app/grants/sync/algorand.py
  app/grants/templates/grants/_new.html
  app/grants/templates/grants/bulk_add_to_cart.html
  app/grants/templates/grants/cart-vue.html
  app/grants/templates/grants/cart/extension/algorand.html
  app/grants/templates/grants/components/card.html
  app/grants/templates/grants/detail/template-grant-details.html
  app/grants/utils.py
  app/grants/views.py
Labels: gpg - crosschain/algorand

#9234 GITC-117: AttributeError: 'NoneType' object has no attribute 'sybil_score'
  app/grants/tasks.py
Labels: hotfix-stable
